### ISSUE TITLE
LDDTool: Enable to ability to set custom namespace base URI in IngestLDD  

### ISSUE THREAD

**Issue by BaptisteCecconi** [NASA-PDS/pds4-information-model#104]
I'm building the VESPA/EPNcore LDD, and I would like to have the XML namespace set as `https://voparis-ns.obspm.fr/pds4/epn/v1`. In the `IngestLDD.xml` file, I can set the `<namespace_id>`, e.g., here `epn`. However the `targetNamespace` attribute in header of the resulting XML schema file, is `http://pds.nasa.gov/pds4/epn/v1`.

How could I specify the full namespace URI in the `IngestLDD` file?

**Comment by jordanpadams** [comment]
@jshughes you mind taking a look at this for @BaptisteCecconi ? is this possible via command-line right now since this is a feature that I'm sure PSA needs as well?

**Comment by jordanpadams** [comment]
@jshughes i believe this can be fixed by getting epn added as a valid namespace in the namespace registry. is that true? or is there another method to doing this?

**Comment by jshughes** [comment]
Correct, the XML namespace should be provided for each new PDS4 namespace. Each new PDS4 namespace must be registered in the PDS4 Namespace Registry. To register a namespace, several items of information associated with the namespace are required, including the XML namespace. Once registered, the new namespace is entered into the config.properties used by the IMTool/LDDTool software. The config file entry for each namespace includes the XML namespace.
