### ISSUE TITLE
PDS4_PDS_1E00.sch inconsistent rules for type of Investigation vs Investigation_Area

### ISSUE THREAD

**Issue by rchenatjpl** [NASA-PDS/pds4-information-model#186]
Investigation/type allows 'Field Campaign'. Investigation_Area/type doesn't. Should it?

Lines 982 to 993:
  <sch:pattern>
    <sch:rule context="pds:Investigation/pds:type">
      <sch:assert test=". = ('Field Campaign', 'Individual Investigation', 'Mission', 'Observing Campaign', 'Other Investigation')">
        The attribute pds:type must be equal to one of the following values 'Field Campaign', 'Individual Investigation', 'Mission', 'Observing Campaign', 'Other Investigation'.</sch:assert>
    </sch:rule>
  </sch:pattern>
  <sch:pattern>
    <sch:rule context="pds:Investigation_Area/pds:type">
      <sch:assert test=". = ('Individual Investigation', 'Mission', 'Observing Campaign', 'Other Investigation')">
        The attribute pds:type must be equal to one of the following values 'Individual Investigation', 'Mission', 'Observing Campaign', 'Other Investigation'.</sch:assert>
    </sch:rule>
  </sch:pattern>

**Comment by jordanpadams** [comment]
@jshughes can you comment on if this is a problem or not?

**Comment by jshughes** [comment]
This issue was resolved with the implementation of CCB-290, "Add value 'Field Campaign' to Investigation_Area type enumerated value list" for IM Version 1.15.0.0, Build 11.0.
