### ISSUE TITLE
LDDTool: requires one class with (element_flag = true), even when no classes defined

### ISSUE THREAD

**Issue by msbentley** [NASA-PDS/pds4-information-model#188]
**Describe the bug**
I am testing the latest LDDTool (0.2.2.1) against a dictionary which does not contain any classes or attributes, only rules.

However, I get a fatal error and no output is generated:

```
ERROR    Class:  - At least one class must be defined as an xs:Element. (<element_flag> set to "true")
```
Is this expected? This is fairly typical in the PSA - we have classes/attributes defined in the PSA dictionary, and we use a mission dictionary Schematron to constrain the values allowed on a per-mission basis, for example....

**Comment by msbentley** [comment]
I realised that in fact output _IS_ created, that was my mistake - so the only issue is that an error is issues when I would not have expected one

**Comment by rchenatjpl** [comment]
Does anyone have an example of such an Ingest_LDD file, one with no class? I built a cr@ppy one for testingl

**Comment by msbentley** [comment]
Hi @rchenatjpl find attached: 
[Ingest_PDS4_PSA_BC_1005.xml.txt](https://github.com/NASA-PDS/pds4-information-model/files/5648513/Ingest_PDS4_PSA_BC_1005.xml.txt) - note that this is designed to work with an old LDDTool (for IM 1B00) plus some hacks to work around issues in the old version, so you will probably have to do some minimal changes to get it to work....

**Comment by rchenatjpl** [comment]
thanks, Mark
