### ISSUE TITLE
LDDtool combining two consecutive choice blocks into one block 

### ISSUE THREAD

**Issue by edguinness** [NASA-PDS/pds4-information-model#192]
LDDtool is combining two consecutive choice blocks defined in the ingest file into one block in the output schema. It causes a problem when min and max occurs are specified. See the Camera_Model_Parameters class in the Geom dictionary.

[ingest-PDS4_GEOM_1D00_1720.xml.txt](https://github.com/NASA-PDS/pds4-information-model/files/4919752/ingest-PDS4_GEOM_1D00_1720.xml.txt)

[PDS4_GEOM_1E00_1720.xsd.txt](https://github.com/NASA-PDS/pds4-information-model/files/4919757/PDS4_GEOM_1E00_1720.xsd.txt)

**Comment by jordanpadams** [comment]
@jshughes have we been able to fix this problem?
