### ISSUE TITLE
CCB-297: Inappropriate values in permissible values list for Product_Observational/Observation_Area/Target_Identification/Internal_Reference/reference_type

### ISSUE THREAD

**Issue by jshughes** [NASA-PDS/pds4-information-model#220]
CCB-297 Inappropriate values in permissible values list for Product_Observational/Observation_Area/Target_Identification/Internal_Reference/reference_type. Deprecate three values, "collection_to_target", "bundle_to_target", and "document_to_target", from the attribute <Product_Observational /Observation_Area /Target_Identification /Internal_Reference /reference_type>.

**Comment by jordanpadams** [comment]
Closed per #221
