### ISSUE TITLE
lddtool-11.4.0-SNAPSHOT version output incorrect

### ISSUE THREAD

**Issue by plawton-umd** [NASA-PDS/pds4-information-model#228]
./lddtool -version
 
LDDTool Version: 10.1.0
Built with IM Version: 1.15.0.0
Build Date: 2020-07-27 16:17:50
Configured IM Versions: [1F00, 1E00, 1D00, 1C00, 1B10, 1B00]
 
Version is not correct.
Build with IM looks fine.
Date seems old.
Configured IM - I cannot comment on.

Per the email received on the 9th of September 2020, the tar.gz file was obtained from 
https://github.com/NASA-PDS/pds4-information-model/releases/tag/11.4.0-SNAPSHOT
(released 21 hours ago)

**Comment by jordanpadams** [comment]
Fixed per a4f374fb8a26be4336ab4995d5cd1d795b523f8f
