### ISSUE TITLE
DocBook HTML/WebHelp generation and conversion processes

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds4-information-model#242]
For the DocBook generation and conversion we need to:
* fix bug with output directory for DocBook (tool should just output wherever you run LDDTool, or create the `./export` directory if it does not exist)
* document how to generate the DocBook XML and then one of two options for generating HTML/WebHelp:
   * using Oxygen - [Webhelp](https://www.oxygenxml.com/xml_editor/webhelp.html), [HTML](https://www.oxygenxml.com/xml_editor/docbook_editor_structured_editing.html)
   * using [Pandoc](https://pandoc.org/) (HTML only) - [examples](https://opensource.com/article/17/9/docbook)

See Epic's sub-tickets for work-to-go.

**Comment by jshughes** [comment]
The WebHelp version of the PDS4 data dictionary document is now being generated for each build along with the HTML and PDF versions of the document. It will also be uploaded to the PDS servers through subversion. The latest version, V1.15.0.0 was just uploaded as a test and includes 1436 files and 12 folders for a total of 13.9 MB.

**Comment by jordanpadams** [comment]
@jshughes does the WebHelp include all LDDs or just the IM?

also, this ticket has 2 sub-tickets associated with it:
#170
#243

if you install the [Zenhub extension for your browser](https://www.zenhub.com/extension) you should be able to see those

**Comment by jordanpadams** [comment]
📆 November Status: On track

**Comment by jordanpadams** [comment]
:calendar: december status: on schedule

**Comment by jordanpadams** [comment]
:calendar: january status: delayed due to work on other bug fixes that were higher priority. still on schedule for completion for B11.1 delivery.
