### ISSUE TITLE
Document how to generate the DocBook XML and how to generate HTML/WebHelp

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds4-information-model#243]
* document how to generate the DocBook XML and then one of two options for generating HTML/WebHelp:
   * using Oxygen - [Webhelp](https://www.oxygenxml.com/xml_editor/webhelp.html), [HTML](https://www.oxygenxml.com/xml_editor/docbook_editor_structured_editing.html)
   * using [Pandoc](https://pandoc.org/) (HTML only) - [examples](https://opensource.com/article/17/9/docbook)

Some instructions from @jshughes:
The process to generate a data dictionary document is as follows:
 
Invoke LDDTool with the -D option and list all of the LDD Ingest_LDD file names you wish to include. (I.e. create a directory stack)
A DocBook formatted file is written to the ./lddtool/export/DD directory, for example "PDS4_PDS_DD_1F00.xml".
 
Example test run from last build.
.\bin\lddtool.bat -lpD PDS4_GEOM_IngestLDD.xml PDS4_CART_1D00_IngestLDD_CART_1933.xml PDS4_IMG_IngestLDD.xml PDS4_IMG_SURFACE_IngestLDD_1B10.xml PDS4_MSN_IngestLDD_1B00.xml PDS4_MSN_SURFACE_IngestLDD_1B00.xml PDS4_PROC_IngestLDD_1B00_1100.xml iput_PDS4_RINGS_1B00_1800.xml > list.txt
 
Load the DocBook file into Oxygen
Under "Configuration Transformation Scenarios" (Wrench icon) choose your desired output formats
HTML - For the Common dictionary we produce and make available one of these for each build.
PDF - For the Common dictionary we produce and make available one of these for each build.
WebHelp Classic - Produces a nice website style document, consisting of a tree of folders. This is what Jordan and I have been discussing.
 
Warning, generating the formatted documents from the DocBook file takes significant time and memory since the DocBook file is typically several megabytes in size. The test run above produced an 8 MB file.
 
The common dictionary HTML and PDF versions take about 30 seconds to generate. The WebHelp version take much longer. I have often gotten "out of memory" errors and had to increase the maximum heap size.

**Comment by tloubrieu-jpl** [comment]
@jordanpadams @nutjob4life  ? @jshughes would like inputs from you on that

**Comment by jordanpadams** [comment]
@tloubrieu-jpl this is not a task for @nutjob4life right now. this is only generated at PDS4 IM build time. eventually it may be nice to get this into CI/CD, but not super critical right now

**Comment by tloubrieu-jpl** [comment]
@jordanpadams, @nutjob4life asked to be involved since he has experience on XML DocBook from other projects he is involved in. I don't think Sean want to do more that giving his opinion/inputs in 15 minutes. I should have mentioned that in my initial comment. This is indeed unrelated to CI/CD for now.

**Comment by jordanpadams** [comment]
@jshughes can we update the LDDTool User Guide to include how to do this?

**Comment by jordanpadams** [comment]
documented here: https://github.com/NASA-PDS/pds4-information-model/wiki/Generating-Data-Dictionary-Documentation
