### ISSUE TITLE
[namespace-registry] add new namespace "<chan1>"

### ISSUE THREAD

**Issue by thareUSGS** [NASA-PDS/pds4-information-model#245]
* **Namespace ID Requested:** chan1
* **Discipline or Mission LDD?** a mission-specific dictionary
* **Steward Organization Name:** PDS GEO and PDS IMG
* **LDD Steward Name:** Susan Slavney and Trent Hare
* **LDD Steward Email:** susan.slavney@wustl.edu
* **LDD Description:** Chandrayaan-1 mission dictionary
* **Rationale for creation of new LDD:** The Chandrayaan-1 mission dictionary contains a class with attributes specific to the 
        Chandrayaan-1 mission and instruments. This dictionary was created for the migration
        of Chandrayaan data products from PDS3 to PDS4.

**Comment by c-suh** [comment]
Updated pds-namespace-registry.pdf uploaded to the [PDS site](https://pds.nasa.gov/datastandards/dictionaries/#namespaces).
