### ISSUE TITLE
Throw WARNING message when enumeration_flag = false but enumerations are specified

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds4-information-model#266]
**Describe the bug**
See pds-data-dictionaries/PDS4-LDD-Issue-Repo#140. In the ticket, it points to the GEOM LDD where:
```
<enumeration_flag>false</enumeration_flag>
```
but `DD_Permissible_Value`s are specified. The output schematron does not include the permissible values.

**Comment by tloubrieu-jpl** [comment]
@jshughes have you been able to look at this ticket ?

**Comment by tloubrieu-jpl** [comment]
The solution would be to have a WARNING instead of the error
