### ISSUE TITLE
[namespace-registry] add new namespace "HYB2"

### ISSUE THREAD

**Issue by c-suh** [NASA-PDS/pds4-information-model#267]
* **Namespace ID Requested:** HYB2
* **Discipline or Mission LDD?** Mission-specific
* **Steward Organization Name:** PDS SBN Node (PSI)
* **LDD Steward Name:** Carol Neese
* **LDD Steward Email:** nees@psi.edu
* **LDD Description:** This is the Hayabusa2 Mission Specific Data Dictionary.
* **Rationale for creation of new LDD:** This dictionary contains classes and attributes specific to the Hayabusa2 mission and instruments. It has been created to support the Hayabusa 2 data archive.

**Comment by c-suh** [comment]
Am requesting more information from @neese in the [original ticket](https://github.com/NASA-PDS/pdsen-operations/issues/38) to post an LDD.

**Comment by rchenatjpl** [comment]
The namespace for hyb2 should be http://darts.isas.jaxa.jp/pds4/mission/hyb2/v1, right? That's the last I heard from Shin-ya Murakami. That didn't happen for me, but I may be running lddtool incorrectly.

% lddtool --version
LDDTool Version: 13.1.0-SNAPSHOT
Built with IM Version: 1.16.0.0
Build Date: 2021-04-08 21:25:01
Configured IM Versions: [1G00, 1F00, 1E00, 1D00, 1C00, 1B10, 1B00]
% lddtool -pl im266lddtoolinput.xml
>>  INFO LDDTOOL Version: 13.1.0-SNAPSHOT
>>  INFO IM Version Id: 1.16.0.0
>>  INFO IM Namespace Id: pds
>>  INFO IM Label Version Id: 1.0
>>  INFO Date: Fri Apr 09 15:03:39 PDT 2021
>>  INFO PARENT_DIR: /Users/rchen/PDS4tools/lddtool
>>  INFO SCRIPT_DIR: /Users/rchen/PDS4tools/lddtool/bin
>>  INFO LIB_DIR: /Users/rchen/PDS4tools/lddtool/lib
>>> INFO Init:  - Config.Properties Namespace Id Found:hyb2
>>> INFO Init:  - Config.Properties Namespace Id Using:hyb2
>>> INFO Init:  - LDD Dictionary_Type is Mission
>>> WARNING Header:  - New steward has been specified:sbn
>>> WARNING Header:  - New namespace id has been specified:hyb2
 -- LDDTool Execution Summary --
     2 warning(s)
     0 error(s)
     0 fatal error(s)
>>  INFO Exit(0)
% ls -tl | head -6
total 238600
-rw-rw-r--  1 rchen  703763885      2782 Apr  9 15:03 PDS4_HYB2_1G00_1G00.xml
-rw-rw-r--  1 rchen  703763885      1809 Apr  9 15:03 PDS4_HYB2_1G00_1G00.sch
-rw-rw-r--@ 1 rchen  703763885      2917 Apr  9 15:03 PDS4_HYB2_1G00_1G00.xsd
-rw-rw-r--  1 rchen  703763885      1884 Apr  9 15:03 PDS4_HYB2_1G00_1G00.csv
-rw-rw-r--  1 rchen  703763885      2257 Apr  9 15:03 PDS4_HYB2_1G00_1G00.txt
% grep hyb2 PDS4_HYB2_1G00_1G00.xsd
  
  
    targetNamespace="http://pds.nasa.gov/pds4/mission/hyb2/v1"
    xmlns:hyb2="http://pds.nasa.gov/pds4/mission/hyb2/v1"
  <xs:element name="Mission_Information" type="hyb2:Mission_Information"> </xs:element>
      <xs:element name="mission_phase_name" type="hyb2:mission_phase_name" minOccurs="1" maxOccurs="unbounded"> </xs:element>
    
[Archive.zip](https://github.com/NASA-PDS/pds4-information-model/files/6288719/Archive.zip)

**Comment by rchenatjpl** [comment]
I want github comments to be plain text. The last comment should have showed that lddtool's output namespace for hyb2 was http://pds.nasa.gov/... instead of http://darts.isas.jaxa.jp/pds4/mission/hyb2/v1

Here's the last email exchange we had with Shin-Ya Murakami
