### ISSUE TITLE
sp ldd does not work with small bodies node data

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds4-information-model#268]
**Describe the bug**

**To Reproduce**

I am trying to load the following datasets in the registry:
https://pds-smallbodies.astro.umd.edu/holdings/pds4-gbo-c2012_s1_ison-v1.0/hfosc_solar-analog/data/derived/
 
I load the dictionary:
https://pds.nasa.gov/pds4/sp/v1/PDS4_SP_1C00_1200.JSON
 
Then I harvest and load in registry the file (registry-manager command) and I get this error:
 
[ERROR] Could not find datatype for field 'sp/Observation_Parameters/sp/spectral_resolution_wavelength'

and

[ERROR] Could not find datatype for field 'sp/Rectangular_FOV/sp/position_angle'

**Expected behavior**
Labels should load in registry, references to datatypes should be found in the LDD JSON file loaded (or we should consider the published data not valid)

**Comment by jshughes** [comment]
Both the XML schema file and the JSON file generated for the latest Spectral LDD (PDS4_SP_1C00_1200) do not have the attributes <sp/Observation_Parameters/sp/spectral_resolution_wavelength> or <sp/Rectangular_FOV/sp/position_angle>. This suggests that the 1C00_1200 version of the Spectral LDD source file does not include definitions for the attributes.

A PDS4 data product label extract from the directory mentioned above references PDS4_SP_1800.xsd (IM V 1.9.0.0). This suggests that the later version of the Spectral LDD does not include the attributes and that the earlier version of the Spectral LDD needs to be used. 

For further information about the Spectral LDD the steward at the SBN, Anne Raugh, needs to be consulted. It seems that the later version of the Spectral LDD is not backwards compatible.

**Comment by tloubrieu-jpl** [comment]
Thanks @jshughes , we (Jordan or I) will contact Anne Raugh on that.

**Comment by jordanpadams** [comment]
@tloubrieu-jpl sent email to SBN

**Comment by jordanpadams** [comment]
@tloubrieu-jpl this is bad data. period. ignore for time being. if this arises as an issue with SBN, we will ask them to fix their data.
