### ISSUE TITLE
The PDS4 IM Specification Document is not consistent in the ordering of Permissible Values

### ISSUE THREAD

**Issue by jshughes** [NASA-PDS/pds4-information-model#269]
The use of alphabetical order within the IM specification is wide spread. Sometimes, for no obvious reason the convention is dropped which can lead the unwary (read lazy) to oversights. 

Alphabetical ordering should be used consistently throughout the document.

See: https://pds.jpl.nasa.gov/datastandards/documents/im/current/index_1E00.html#attribute_pds_internal_reference_pds_reference_type

Extended Values for: pds:Product_Context/pds:Reference_List/pds:Internal_Reference
…
- resource_to_target - The resource is associated to a target
- target_to_document - The target is associated to a document
- target_to_instrument - The target is associated to an instrument
- target_to_instrument_host - The target is associated to an instrument_host
- target_to_investigation - The target is associated to an investigation
- instrument_to_telescope - The instrument is associated to a telescope
- instrument_to_observatory - The instrument is associated to an observatory
- instrument_to_facility - The instrument is associated to a facility
- telescope_to_observatory - The telescope is associated to an observatory
- telescope_to_facility - The telescope is associated to a facility
- telescope_to_airborne - The telescope is associated to an airborne platform
- investigation_to_facility - The investigation is associated to a facility
- investigation_to_telescope - The investigation is associated to a telescope
- facility_to_investigation - The facility is associated to an investigation
- facility_to_instrument - The facility is associated to an instrument
- facility_to_telescope - A facility is associated to a telescope
- investigation_to_facility - The investigation is associated to a facility
- telescope_to_instrument - A telescope is associated to an instrument

**Comment by nutjob4life** [comment]
A node staffer is not quite as pleased with the way things are ordered; but this is an a less-used document, so this is of lower priority.

**Comment by jpl-jengelke** [comment]
[testdata.zip](https://github.com/NASA-PDS/pds4-information-model/files/8674058/testdata.zip)
