### ISSUE TITLE
CCB-323: Fix schema formation rule for lidvid_reference (Part II)

### ISSUE THREAD

**Issue by rchenatjpl** [NASA-PDS/pds4-information-model#270]
I've successfully ingested a few context products whose LIDs include +. They did validate correctly. Now when one is listed in a collection.xml's csv, validate complains.

I'm going to assume + is a legal character. If that's wrong, please let me know ASAP, and I'll have a lot to fix.
[Archive.zip](https://github.com/NASA-PDS/validate/files/4957001/Archive.zip)

**Comment by jordanpadams** [comment]
Per comment from @rchenatjpl on the SCR, this appears to have been fixed as part of other bug fixes in 1E00+
