### ISSUE TITLE
LDDTool forces use of LDD versions based upon config

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds4-information-model#271]
**Describe the bug**
So the img_surface IngestLDD references GEOM v1810, IM v1E00

```
<Ingest_LDD
    xmlns="http://pds.nasa.gov/pds4/pds/v1"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:img_surface="http://pds.nasa.gov/pds4/img_surface/v1"
    xmlns:geom="http://pds.nasa.gov/pds4/geom/v1"
    xmlns:pds="http://pds.nasa.gov/pds4/pds/v1"
    xsi:schemaLocation="https://pds.nasa.gov/pds4/pds/v1 https://pds.nasa.gov/pds4/pds/v1/PDS4_PDS_1E00.xsd
    http://pds.nasa.gov/pds4/geom/v1 https://pds.nasa.gov/pds4/geom/v1/PDS4_GEOM_1E00_1810.xsd">
```

We then ran lddtool for img_surface for IM v1F00 and used GEOM v1900, IM v1F00.
 
But then the output when we generate the img_surface XSD references GEOM  v1700, IM v1F00.
 
```
    <xs:import namespace="http://pds.nasa.gov/pds4/pds/v1" schemaLocation="https://pds.nasa.gov/pds4/pds/v1/PDS4_PDS_1F00.xsd"/>
    <xs:import namespace="http://pds.nasa.gov/pds4/geom/v1" schemaLocation="https://pds.nasa.gov/pds4/geom/v1/PDS4_GEOM_1F00_1700.xsd"/>
 ```
 
So I guess I don’t understand how GEOM v1700 even got into the mix here? We did not refer to it anywhere in any of the files we are using

---

The “1700” is coming from the config.properties file, as you can see from the snippet below. The reason I couldn’t replicate the error is that I have removed the versionId entries from the config.properties file for the March 2021 build. These entries are “left-overs” from the LDD ingest phase of the IM. 
 
But there remains a bug. The versionId from the Ingest_LDD is not being used for the import statements. That is being fixed now.
 
```
                             lSchemaFileDefn.geo.identifier=geo
                             lSchemaFileDefn.geo.versionId=1.7.0.0
                             lSchemaFileDefn.geo.labelVersionId=1.21
                             lSchemaFileDefn.geo.isMaster=false
                             lSchemaFileDefn.geo.isDiscipline=true
                             lSchemaFileDefn.geo.stewardArr=geo
                            lSchemaFileDefn.geo.nameSpaceURL=http://pds.nasa.gov/pds4/
                            lSchemaFileDefn.geo.nameSpaceURLs=https://pds.nasa.gov/pds4/
                             lSchemaFileDefn.geo.urnPrefix=urn:nasa:pds:
                             lSchemaFileDefn.geo.modelShortName=PDS4
                             lSchemaFileDefn.geo.regAuthId=0001_NASA_PDS_1
```

**Comment by rchenatjpl** [comment]
Please, someone make available the Ingest_LDD files. Transparency is a good thing.

**Comment by jordanpadams** [comment]
@rchenatjpl some versions of these are out at https://github.com/pds-data-dictionaries . Sorry for not attaching the failing dictionaries, but you should be able to find the ing_surface LDD in that GitHub repo. Also, in the future try to @mention whenever possible on these tickets, otherwise these comments tend to get buried in the weeds

**Comment by rchenatjpl** [comment]
Thanks, Jordan. That directory is helpful.
