### ISSUE TITLE
CCB-321: Add MPEG-4 as an encoding_standard_id for Product_Native

### ISSUE THREAD

**Issue by jshughes** [NASA-PDS/pds4-information-model#288]
https://pds-jira.jpl.nasa.gov/browse/CCB-321

Add the permissible value “MPEG-4” and its value meaning to the attribute <Encoded_Native.encoding_standard_id>. This change allows video and audio streams from missions like Mars 2020 to be recognized as science artifacts in the archive.

**Comment by jordanpadams** [comment]
Withdraw by author

[Uploading CCB-321.pdf…]()
