### ISSUE TITLE
LDDTool does not allow the bundle to be specified for generated dictionaries

### ISSUE THREAD

**Issue by msbentley** [NASA-PDS/pds4-information-model#302]
**Describe the bug**
When using LDDTool to generate non-PDS dictionaries, a PDS-specific LID is generated in the dictionary label, for example:

`urn:psa:esa:system_bundle:xml_schema:psa-xml_schema_1.15.0.0_1.3.0.0`

for the PSA dictionary. The agency LID stem is set correctly, but we do not use a bundle `system_bundle`. 

Issue #303 contains Ingest files that can be used for testing.

**Expected behavior**

Either a way is needed to specify the bundle where the output label should live, or this could be added to the namespace registry.

**Version of Software Used**
```
LDDTool Version: 12.1.0
Built with IM Version: 1.15.0.0
Build Date: 2021-01-11 12:52:30
Configured IM Versions: [1F00, 1E00, 1D00, 1C00, 1B10, 1B00]
```

**Desktop (please complete the following information):**
 - OS: linux
 - Version: ubuntu 20.04

**Comment by jshughes** [comment]
> Either a way is needed to specify the bundle where the output label should live, or this could be added to the namespace registry.

A reasonable technical solution is to specify the bundle in the namespace registry/config.properties file. However, the impact of this change on PDS best practices, policies, and the system in general probably needs to be discussed by the DDWG.

**Comment by gxtchen** [comment]
Can someone explain how is this issue fixed? Does the user need to use specify the bundle in the namespace registry/config.properties file?

**Comment by jordanpadams** [comment]
@jshughes can you help out @gxtchen here?

@gxtchen if you can, please try to use GitHub mentions with @somebody whenever you need a response. We have lots of repositories and lots of traffic coming over via email, and the mentions help pull out the ones a specific person needs to respond to. 🎉

**Comment by jshughes** [comment]
The issue was fixed by adding line to the config.properties file for those namespaces that do not default to the "pds" bundle name. For example, "SchemaFileDefn.psa.sysBundleName=psa_master" was added for the namespace "psa". To add new bundle name, submit a new "PDS Namespace Request". If a namespace already exists, please specify it in the request. If namespace does not exist then please specify that the namespace needs to be be added as well.
