### ISSUE TITLE
LDDTool does include the PSA namespace

### ISSUE THREAD

**Issue by jshughes** [NASA-PDS/pds4-information-model#304]
When the PSA Ingest_LDD files Ingest_PDS4_PSA_1201.xml and Ingest_PDS4_PSA_BC_1005.xml are processed by LDDTool the resulting XML Schema file does not contain the PSA namespace declaration. In addition, the BC namespace is written however it is not correct. It contains duplicate terms.

The Ingest_LDD file Ingest_PDS4_PSA_BC_1005 is unique since it defines only rules. No classes or attributes are defined in the file.

The PSA namespace and a correct BC namespace should be written to the XML Schema file.

**Comment by rchenatjpl** [comment]
@jordanpadams @jshughes Sample Ingest_LDD files, please

**Comment by jordanpadams** [comment]
@jshughes can you please attach the IngestLDD files referenced in the original ticket description?

**Comment by jshughes** [comment]
[](url)

**Comment by jshughes** [comment]
There are two sets of IngestLDD files, the original and later versions. (App does not seem to accept .xml files. XML extension has been changed to TXT)

-original-
[Ingest_PDS4_PSA_1201 - Copy.txt](https://github.com/NASA-PDS/pds4-information-model/files/6345059/Ingest_PDS4_PSA_1201.-.Copy.txt)
[Ingest_PDS4_PSA_BC_1005 - Copy.txt](https://github.com/NASA-PDS/pds4-information-model/files/6345060/Ingest_PDS4_PSA_BC_1005.-.Copy.txt)

-later-
[Ingest_PDS4_PSA_BC_1100 - Copy.txt](https://github.com/NASA-PDS/pds4-information-model/files/6345079/Ingest_PDS4_PSA_BC_1100.-.Copy.txt)
[Ingest_PDS4_PSA_1300 - Copy.txt](https://github.com/NASA-PDS/pds4-information-model/files/6345080/Ingest_PDS4_PSA_1300.-.Copy.txt)

**Comment by jordanpadams** [comment]
@rchenatjpl ☝️
