### ISSUE TITLE
Refactoring of IMTool

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds4-information-model#306]

**Comment by jordanpadams** [comment]
📆 June status: De-scoping this effort until next build due to https://github.com/nasa-pds/pds4-information-model/issues/368. approval pending from SWG. see https://github.com/NASA-PDS/pds-swg/issues/11

**Comment by jordanpadams** [comment]
📆 November status: Start date delayed due to delay in #401. No expected impact on build delivery.

**Comment by nutjob4life** [comment]
In progress!

**Comment by jordanpadams** [comment]
📆 December status: On schedule

**Comment by jordanpadams** [comment]
Not done yet...

**Comment by jordanpadams** [comment]
all sub-tasks completed
