### ISSUE TITLE
Make ROOT element check namespace-aware

### ISSUE THREAD

**Issue by sxntxn** [NASA-PDS/pds4-information-model#315]
The root-element declaration:
```
<pds:Product_Observational xmlns:pds="http://pds.nasa.gov/pds4/pds/v1" >
```
is semantically equivalent to:
```
<Product_Observational xmlns="http://pds.nasa.gov/pds4/pds/v1" >
```
... so it should also be accepted as correct, i.e., it won't trigger the
```
The ROOT element must be one of the allowed types.
```
error message anymore.

I've prepared a patch for this for VALIDATE, which was the wrong place, as it turns out. 
See the original commit proposing the change here:
https://github.com/sxntxn/validate/commit/0e31700e9bca202947cdf76eeeefe2762a05c6f7

Please let me know what you think.
If you think it's worthwhile, please let me know which is the actual source code file (grepping for the error message gives me 14 files: which to patch?).

**Comment by jordanpadams** [comment]
@sxntxn we talked about this with some folks on our Data Design Working Group and even though `pds:Product_Observational` is semantically equivalent to `Product_Observational` in XML, the PDS4 Standard requires `Product_Observational`.

is there some specific use case or data products you are trying to implement this for? we can put you in touch with one of our PDS Discipline Nodes, who can help you sift through some of the standards and help with guidance in some of these areas.
