### ISSUE TITLE
[namespace-registry] add new namespace "multi"

### ISSUE THREAD

**Issue by jmafi** [NASA-PDS/pds4-information-model#319]
* **Namespace ID Requested:** multi
* **Discipline or Mission LDD?** Discipline
* **Steward Organization Name:** PDS PPI Node
* **LDD Steward Name:** Joseph Mafi
* **LDD Steward Email:** jmafi@igpp.ucla.edu
* **LDD Description:** The Multidimensional dictionary contains classes that describe relationships between multidimensional data objects contained within a single data product.
* **Rationale for creation of new LDD:** These classes are needed in order to describe the relationships between multidimensional array objects. They replicate the DEPEND_n attributes provided in CDF metadata. These classes were previously defined in v1 of the Particle dictionary, however, they apply to more than just particle data.

**Comment by jordanpadams** [comment]
@jshughes @c-suh FYI, can we get this added ASAP?

**Comment by c-suh** [comment]
Updated .pdf has been posted to https://pds.nasa.gov/datastandards/dictionaries/index-1.15.0.0.shtml#namespaces.
