### ISSUE TITLE
[namespace-registry] add new namespace "<clementine>"

### ISSUE THREAD

**Issue by thareUSGS** [NASA-PDS/pds4-information-model#332]
* **Namespace ID Requested:** clementine
* **Discipline or Mission LDD?** mission-specific dictionary
* **Steward Organization Name:** IMG, GEO
* **LDD Steward Name:** Trent Hare
* **LDD Steward Email:** thare@usgs.gov
* **LDD Description:** The Clementine mission dictionary contains a class with attributes specific to the Deep Space Program Science Experiment, including the Clementine orbiter and its instruments. This dictionary was created for the migration of Clementine data products from PDS3 to PDS4 by Million Concepts (contact M. St. Clair). The dictionary has been created and will be transitioned to PDS' github dictionary site. https://github.com/MillionConcepts/ldd-clementine
* **Rationale for creation of new LDD:** To support the Clementine mission for PDS4

---

**Engineering Details**
- [x] @jshughes update namespace registry
- [x] @c-suh if dLDD and [repo exists here](https://github.com/pds-data-dictionaries/) update [LDD script config](https://github.com/NASA-PDS/pdsen-operations/blob/master/conf/ldds/config.yml)

**Comment by tloubrieu-jpl** [comment]
@jshughes will work on that next week

**Comment by jordanpadams** [comment]
closed per https://github.com/NASA-PDS/pds4-information-model/pull/354. mission LDD
