### ISSUE TITLE
CCB-328 : Inconsistency in <title> type definition

### ISSUE THREAD

**Issue by jshughes** [NASA-PDS/pds4-information-model#339]
The IM Common dictionary and its generated Schema file are not consistent since the attribute <title> in the IM is defined with two different data types where in the generated Schema file only one data type is allowed. This is a bug since XML Schema allows only one definition of an attribute.

This can be observed by comparing the five definitions of <title> in the PDS4 data dictionary with the definition of the pds:title element in the generated XML Schema file.

1.	title in Identification_Area -- UTF8_Short_String_Collapsed
2.	title in Composite_Structure -- ASCII_Short_String_Collapsed
3.	title in Property_Map -- ASCII_Short_String_Collapsed
4.	title in Property_Maps -- ASCII_Short_String_Collapsed¬
5.	title in Terminological_Entry_SKOS -- ASCII_Short_String_Collapsed

CCB-328, "Inconsistency in <title> type definition" suggests that the data types of the attribute <title> in the IM be changed to UTF8_Short_String_Collapsed. 

This will effect V1.16.0.0

**Comment by jordanpadams** [comment]
@jshughes is this a bug? or an SCR?

**Comment by jshughes** [comment]
It is an actual SCR. However in reality it is a bug and the DDWG is treating it as a bug. This means that CCB review is cursory.
