### ISSUE TITLE
[namespace-registry] add new namespace "ctli"

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds4-information-model#344]
* **Namespace ID Requested:** ctli
* **Discipline or Mission LDD?** Discipline
* **Steward Organization Name:** PDS ATM Node
* **LDD Steward Name:** Lyle Huber
* **LDD Steward Email:** lhuber@nmsu.edu
* **LDD Description:** The CTLI dictionary provides a set of type values for instruments for use in instrument context products.
* **Rationale for creation of new LDD:** This LDD was created a while back through DDWG but never added to namespace registry.

---

**Engineering Details**
- [x] @jshughes update namespace registry
- [x] @c-suh if dLDD and [repo exists here](https://github.com/pds-data-dictionaries/) update [LDD script config](https://github.com/NASA-PDS/pdsen-operations/blob/master/conf/ldds/config.yml)

**Comment by tloubrieu-jpl** [comment]
@jshughes will work on that next week

**Comment by jordanpadams** [comment]
closed per https://github.com/NASA-PDS/pds4-information-model/pull/354

**Comment by jordanpadams** [comment]
closed per https://github.com/NASA-PDS/pds4-information-model/pull/354. already part of dLDD script
