### ISSUE TITLE
lddtool's doc directory is not in tgz file

### ISSUE THREAD

**Issue by plawton-umd** [NASA-PDS/pds4-information-model#346]
**Describe the bug**

The lddtool-13.0.2/README.txt file references ./doc/index.html.  The file is 
not available since the doc directory does not exist.

**Expected behavior**

The doc directory to be accessible - specifically to read installation information.

**Test Data**
Attach test data here
```
> cd lddtool-13.0.2
> ls
bin   Examples  Extract  LICENSE.txt           README.txt
Data  export    lib      Model_DataDictionary  SchemaXML4
```
**Related Test Case(s)**
Document related test cases here

n/a

**Comment by jordanpadams** [comment]
@plawton-umd could you send over how you attempted to execute the tool?

**Comment by jordanpadams** [comment]
@plawton-umd oops. Nevermind. I see the issue in the documentation.

**Comment by jordanpadams** [comment]
this was user error in tagging a manual release and not running the `mvn site` command. fixed packages have been uploaded. see https://github.com/NASA-PDS/pds4-information-model/releases/tag/v13.0.2
