### ISSUE TITLE
Contradictory DISP rule assertions exist in the PDS4 IM from legacy ingestion

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds4-information-model#351]
## 🐛 Describe the bug
Per https://github.com/pds-data-dictionaries/PDS4-LDD-Issue-Repo/issues/143:

there are three DISP rule assertions in the IM database. They will be removed from the IM database.

1) The rule assertion with the error message,  "In the pds:Local_Internal_Reference class, the value of the pds:local_identifier_reference  ... " was written to enforce referential integrity. In other words, the <local_identifier_reference> must have a matching <local_identifer>. Since the data types of these attributes have been changed to xsd:IDREF and xsd:ID respectively, this rule might not be needed. I will ping Ron Joyner. He wrote the rule and there may be an issue with the use of external name spaces.

2) Whether "display_to_data_object" or "display_settings_to_array" is a decision to be made by the DISP LDD stewards.

3) The third rule assertion might need to be added to the LDD. I believe that Elizabeth wrote it. Given the latest .xsd file, it seems that the <Display_Direction> is not required to be nested within Display_Settings. 

		assert: if (disp:Display_Direction) then (disp:Display_Settings/disp:Display_Direction) else true()
		
				Display Dictionary: If the Display_Direction class is in the label, it 
				must be contained in a Display_Settings class.

--- Rule Assertions found in the IM database.

	http://pds.nasa.gov/infomodel/pds#.disp:Display_Settings/pds:Local_Internal_Reference.100002511
	disp:Display_Settings/pds:Local_Internal_Reference
	
		1) assert: pds:local_identifier_reference =
			//pds:*/pds:*/(pds:Array|pds:Array_2D|pds:Array_2D_Image|pds:Array_2D_Map|pd
			s:Array_2D_Spectrum|pds:Array_3D|pds:Array_3D_Image|pds:Array_3D_Movie|pds:A
			rray_3D_Spectrum)/pds:local_identifier

				Display Dictionary: In the pds:Local_Internal_Reference class, the value
				of the pds:local_identifier_reference must match the value of the
				pds:local_identifer of an Array class or sub-class within the File_Area.

		2) assert: pds:local_reference_type = ('display_settings_to_array')

				Display_Dictionary: In the pds:Local_Internal_Reference class, the value
				of the pds:local_reference_type must be 'display_settings_to_array'.                  
				
				
	http://pds.nasa.gov/infomodel/pds#.disp:Discipline_Area.100002510				
	
		3) assert: if (disp:Display_Direction) then (disp:Display_Settings/disp:Display_Direction) else true()
		
				Display Dictionary: If the Display_Direction class is in the label, it
				must be contained in a Display_Settings class.

**Comment by jshughes** [comment]
Reviewing the resolution of the original Issue#143, the three rule assertions with the following error messages were removed from the Common dictionary.

1. Display Dictionary: In the pds:Local_Internal_Reference class, the value of the pds:local_identifier_reference must match the value of the pds:local_identifer of an Array class or sub-class within the File_Area. 
2. Display_Dictionary: In the pds:Local_Internal_Reference class, the value of the pds:local_reference_type must be 'display_settings_to_array'. 
3. Display Dictionary: If the Display_Direction class is in the label, it must be contained in a Display_Settings class.

There remain three rules assertions associated with pds:Display_2D_Image, which has been deprecated. One of these assertions fires a Warning if pds:Display_2D_Image is found. The other two rule assertions remain for backwards compatibility.

I believe that all other issues are external to the Common dictionary and have been resolved.

**Comment by jpl-jengelke** [comment]
[testdata.zip](https://github.com/NASA-PDS/pds4-information-model/files/8674078/testdata.zip)
