### ISSUE TITLE
[namespace-registry] add new namespace "ml"

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds4-information-model#353]
* **Namespace ID Requested:** ml (lower case ML)
* **Discipline or Mission LDD?** discipline
* **Steward Organization Name:** PDS IMG
* **LDD Steward Name:** Michael Mcauley
* **LDD Steward Email:** Michael.McAuley@jpl.nasa.gov
* **LDD Description:** Machine Learning Classifier Discipline Local Data Dictionary
* **Rationale for creation of new LDD:** Specifying metadata generated by machine learning algorithms associated with PDS observational products

---

**Engineering Details**
- [x] @jshughes update namespace registry
- [x] @c-suh if dLDD and [repo exists here](https://github.com/pds-data-dictionaries/) update [LDD script config](https://github.com/NASA-PDS/pdsen-operations/blob/master/conf/ldds/config.yml)

**Comment by jordanpadams** [comment]
@myche @wkiri FYI. this is per this warning you will get when you generate your LDD: 
```
>>> WARNING Init:  - Config.Properties Namespace Id Not Found:ml
```

**Comment by myche** [comment]
Hmm .. OK.  Does this mean that the `ml` namespace needs to be added to some master LDD config file somewhere?

**Comment by jordanpadams** [comment]
updated per https://github.com/NASA-PDS/pds4-information-model/pull/354 . still in dev phase so no need to add to online config yet

**Comment by jordanpadams** [comment]
@myche correct. in order to avoid the warning about the missing namespace, we need to add this to an LDDTool internal config
