### ISSUE TITLE
Ingest PDS4 IM into BlazeGraph

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds4-information-model#357]
[PDS4_PDS_RDFTTLALL_1G00.ttl.zip](https://github.com/NASA-PDS/pds4-information-model/files/6495449/PDS4_PDS_RDFTTLALL_1G00.ttl.zip)

**Comment by TWilson2017** [comment]
![image](https://user-images.githubusercontent.com/25163556/120501964-0914d800-c390-11eb-8cd2-ec2b0ed7a5e7.png)
Turtle file uploaded

**Comment by TWilson2017** [comment]
![image](https://user-images.githubusercontent.com/25163556/120502117-28ac0080-c390-11eb-81a6-ac93adb00e4a.png)
Query to get type based off the rdfs:label equaling "Bounding_Coordinates"

**Comment by TWilson2017** [comment]
![image](https://user-images.githubusercontent.com/25163556/120502749-b0920a80-c390-11eb-9c25-6a0462ee5cc0.png)
Query data returned
