### ISSUE TITLE
Replicate diagram from PDS4 IM Spec

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds4-information-model#358]
Try to replicate some form of the PDS4 IM Spec diagram from here:

https://pds.nasa.gov/datastandards/documents/im/v1/index_1F00.html#4%C2%A0%C2%A0Scope

**Comment by tloubrieu-jpl** [comment]
The sparql server does not start yet (errors)

**Comment by tloubrieu-jpl** [comment]
The sparql file was updated, wil be send to @jshughes

**Comment by jordanpadams** [comment]
**2021-06-17 Tasks**
- [X] fix TTL file with slash issue
- [X] send Jordan/Thomas the issue you are seeing with the TTL file
- [ ] visualize the context products

**2021-06-24 Tasks**
- [ ] Revise the search for products which subClassIs context
- [ ] Visualize the context products

**Comment by jordanpadams** [comment]
Next tasks
- [ ] refine the context product diagram to look similar to the context product defined on the IM spec page
   - [ ] filter down the context products shown

**Comment by jordanpadams** [comment]
- [ ] @TWilson2017 research Sparql in more detail to better understand how to manipulate the more complex queries

**Comment by tloubrieu-jpl** [comment]
Next tasks:

- [ ] integrate graph request into main notebook and do some cleaning
- [ ] do the data import from the turtle uploaded on the notebook server (instead of from a block pasted in the notebook)
- [ ] import the rdfs schema from https://www.w3.org/2000/01/rdf-schema
- [ ] replace edge label with "subClassOf"

**Comment by jordanpadams** [comment]
@TWilson2017 tasks:
- [ ] draft email with the following information for @jshughes:
   - [ ] update made to RDF schema
   - [ ] query of database
   - [ ] output visualization
   - [ ] question: how do we update the PDS4 TTL file to do this mapping between `subClassOf` and `pds4:label`

**Comment by jordanpadams** [comment]
@TWilson2017 tasks:
- [ ] create a similar query as context product for Product
- [ ] create a similar query as context product for Array
- [ ] develop python script to convert PDS4 XML to RDF

**Comment by jordanpadams** [comment]
@TWilson2017 new tasks:
- [ ] create a similar query as context product for Array
    - [ ] send email to @jshughes per the issues found regarding `pds4:urn:nasa:pds:array::1.0` sub class usage
    - [ ] update file manually to use `pds4:urn:nasa:pds:byte_stream:array::1.0`
- [ ] develop python script to convert PDS4 XML to RDF

**Comment by tloubrieu-jpl** [comment]
@TWilson2017 new tasks:

Today:

- [ ] use the latest version of steve's ttl file (by replace in an editor \/ with \\//) and make array and context product graph work. The new edge label should be "is_a"
[PDS4_PDS_RDFTTL_1H00.ttl.zip](https://github.com/NASA-PDS/pds4-information-model/files/6894945/PDS4_PDS_RDFTTL_1H00.ttl.zip)
