### ISSUE TITLE
Deploy new Amazon Neptune instance for PDS4 IM prototype

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds4-information-model#359]

**Comment by tloubrieu-jpl** [comment]
Ned to create an S3 bucket

**Comment by jordanpadams** [comment]
Neptune deployed. Creating new ticket to test with S3 later on.

**Comment by jordanpadams** [comment]
https://github.com/NASA-PDS/pds4-information-model/wiki/AWS-Neptune
