### ISSUE TITLE
B12.0 Evolution of DD_Associate_External_Class

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds4-information-model#368]
Evolution of CCB-256: Need method for providing permissible value definitions for external namespaces in Ingest_LDD.

https://pds-jira.jpl.nasa.gov/browse/CCB-256

### Engineering Details
* New `DD_Associate_External_Class` class identified
* Continue to work various bugs and enhancements needed to ensure this does not break the rest of the system

**Comment by jordanpadams** [comment]
📆 June Status: New task added to track work being done to support GEOM LDD split efforts

**Comment by jordanpadams** [comment]
📆 July Status: WIP. continuing to deal with DD_AEC issues

**Comment by jshughes** [comment]
The latest release of LDDTool produced the correct .xsd and .sch files for the partitioned Geometry LDD, namely the Ingest_LDD files GeomImageDisplay.xml GeomLander.xml GeomOrbit.xml and GeomMain.xml.  A. Raugh will continue testing.

**Comment by jordanpadams** [comment]
All sub-tasks completed. Will create new tickets if there are continuing issues.
