### ISSUE TITLE
LDDTool documentation inconsistency

### ISSUE THREAD

**Issue by seanhardman** [NASA-PDS/pds4-information-model#375]
## 🐛 Describe the bug
I believe this issue is more of a documentation inconsistency than an actual bug. In the tool help, it states that the "-M" flag has been deprecated:

> The -M flag has been deprecated as of PDS4 IM Version 1.14.0.0. See the LDDTool User's Manual for more information on how to provide this information.

It references the "LDDTool User's Manual", but it is not clear where that document can be found. I reviewed the "Usage" guide at https://nasa-pds.github.io/pds4-information-model/model-lddtool/usage/index.html and there does not appear to be any information regarding Mission dictionaries in that document. There are some inconsistencies in this document though. The table of contents lists sections "Generating Discipline LDDs" and "Generating Mission LDDs" that are not found in that document.

I also reviewed the "Operation" guide at https://github.com/NASA-PDS/pds4-information-model/blob/main/model-lddtool/operation.md and there does not appear to be any information regarding Mission dictionaries in that document either.

So, if it is documented somewhere, linking to it appropriately will likely resolve this issue. That said, it does appear that specifying the "-M" flag does impact the result of generating a dictionary. See the details below where key results are **bolded**.

### Running the lddtool without specifying the "-M" flag

(base) MT-202412:bin shardman$ ./lddtool -lp PDS4_CLIPPER_IngestLDD.xml

INFO LDDTOOL Version: 13.0.2
INFO IM Version Id: 1.16.0.0
INFO IM Namespace Id: pds
INFO IM Label Version Id: 1.0
INFO Date: Wed Jun 23 10:25:53 PDT 2021
INFO PARENT_DIR: /Users/shardman/dev/eurc/lddtool-13.0.2
INFO SCRIPT_DIR: .
INFO LIB_DIR: /Users/shardman/dev/eurc/lddtool-13.0.2/lib

**ERROR Init:  - LDD Dictionary_Type not Found:TBD_dictionary_type  Defaulting to Discipline**
...

The processing report contains:

PDS4 Local Data Dictionary Processing Report
  
Configuration:
   LDDTool Version        13.0.2
   LDD Version Id:        1.0.0.0
   LDD Label Version Id:  1.0
   LDD Discipline (T/F):  true
   LDD Namespace URL:     http://pds.nasa.gov/pds4/
   LDD URN Prefix:        urn:nasa:pds:
   Time                   Wed Jun 23 10:34:24 PDT 2021
   Common Schema          [PDS4_PDS_1G00.xsd]
   Common Schematron      [PDS4_PDS_1G00.sch]
   IM Version Id:         1.16.0.0
   IM Namespace Id:       pds
   IM Label Version Id:   1.0
   IM Object Model        [UpperModel.pont]
   IM Data Dictionary     [dd11179.pins]
   IM Configuration File  [MDPTNConfigClassDisp.xml]
   IM Glossary            [Glossary.pins]
   IM Document Spec       [DMDocument.pins]

Parameters:
   Input File             [PDS4_CLIPPER_IngestLDD.xml]
   PDS Processing         true
   LDD Processing         true
   **Discipline LDD         true
   Mission LDD            false**
   Write Attr Elements    false
   Merge with Master      false

The resulting schema contains:

  <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    **targetNamespace="http://pds.nasa.gov/pds4/clipper/v1"
    xmlns:clipper="http://pds.nasa.gov/pds4/clipper/v1"**
    xmlns:pds="http://pds.nasa.gov/pds4/pds/v1"
    elementFormDefault="qualified"
    attributeFormDefault="unqualified"
    version="1.0.0.0">

### Running the lddtool with specification of the "-M" flag

(base) MT-202412:bin shardman$ ./lddtool -lpM PDS4_CLIPPER_IngestLDD.xml

INFO LDDTOOL Version: 13.0.2
INFO IM Version Id: 1.16.0.0
INFO IM Namespace Id: pds
INFO IM Label Version Id: 1.0
 INFO Date: Wed Jun 23 10:29:48 PDT 2021
INFO PARENT_DIR: /Users/shardman/dev/eurc/lddtool-13.0.2
INFO SCRIPT_DIR: .
INFO LIB_DIR: /Users/shardman/dev/eurc/lddtool-13.0.2/lib
WARNING The -M flag has been deprecated as of PDS4 IM Version 1.14.0.0. See the LDDTool User's Manual for more information on how to provide this information.
...
**INFO Init:  - LDD Dictionary_Type is Mission**

The processing report contains:

PDS4 Local Data Dictionary Processing Report
  
Configuration:
   LDDTool Version        13.0.2
   LDD Version Id:        1.0.0.0
   LDD Label Version Id:  1.0
   LDD Discipline (T/F):  false
   LDD Namespace URL:     http://pds.nasa.gov/pds4/
   LDD URN Prefix:        urn:nasa:pds:
   Time                   Wed Jun 23 10:29:48 PDT 2021
   Common Schema          [PDS4_PDS_1G00.xsd]
   Common Schematron      [PDS4_PDS_1G00.sch]
   IM Version Id:         1.16.0.0
   IM Namespace Id:       pds
   IM Label Version Id:   1.0
   IM Object Model        [UpperModel.pont]
   IM Data Dictionary     [dd11179.pins]
   IM Configuration File  [MDPTNConfigClassDisp.xml]
   IM Glossary            [Glossary.pins]
   IM Document Spec       [DMDocument.pins]

Parameters:
   Input File             [PDS4_CLIPPER_IngestLDD.xml]
   PDS Processing         true
   LDD Processing         true
   **Discipline LDD         false
   Mission LDD            true**
   Write Attr Elements    false
   Merge with Master      false

The resulting schema contains:

  <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    **targetNamespace="http://pds.nasa.gov/pds4/mission/clipper/v1"
    xmlns:clipper="http://pds.nasa.gov/pds4/mission/clipper/v1"**
    xmlns:pds="http://pds.nasa.gov/pds4/pds/v1"
    elementFormDefault="qualified"
    attributeFormDefault="unqualified"
    version="1.0.0.0">

## 🕵️ Expected behavior
I guess I expected the "-M" flag not to impact the schema output.

## 📚 Version of Software Used
13.0.2

## 🩺 Test Data / Additional context
N/A

##  🏞Screenshots
N/A

## 🖥 System Info
 - OS: Mac OS 10.15.7
 - Browser N/A
 - Version N/A

---

** :unicorn: Applicable requirements**

**Comment by jpl-jengelke** [comment]
[testdata.zip](https://github.com/NASA-PDS/pds4-information-model/files/8674075/testdata.zip)
