### ISSUE TITLE
[namespace-registry] add new namespace "Earth-Based Telescope Namespace"

### ISSUE THREAD

**Issue by acraugh** [NASA-PDS/pds4-information-model#386]
* **Namespace ID Requested:** ebt
* **Discipline or Mission LDD?** Discipline
* **Steward Organization Name:** PDS Small Bodies Node
* **LDD Steward Name:** Ben Hirsch
* **LDD Steward Email:** bhirsch1@umd.edu
* **LDD Description:** This namespace will provide observing parameters, provenance, and geometry relevant to ground-based telescopes on Earth and for Earth-orbiting (or Lagrange point) telescopes
* **Rationale for creation of new LDD:** The types of calibration, filter descriptions, and geometry used in characterizing telescope data from these sources is inherently different from spacecraft-based observations. While there is some minor overlap in geometry concepts, the coordinates are typically two-dimensional (RA and Dec) or defined in FITS WCS, and thus are more aligned with the terminology and usage of astrophysics observatories than planetary orbiter/flyby missions. (Note that Anne Raugh (araugh@umd.edu) will be supporting the creation/configuration effort as needed.)
---

**Engineering Details**
- [ ] @jshughes update namespace registry
- [ ] @c-suh if dLDD and [repo exists here](https://github.com/pds-data-dictionaries/) update [LDD script config](https://github.com/NASA-PDS/pdsen-operations/blob/master/conf/ldds/config.yml)

**Comment by acraugh** [comment]
Ben's GitHub handle is @benjhirsch.

**Comment by c-suh** [comment]
Note: repo does not exist, so have not updated the [LDD script config](https://github.com/NASA-PDS/pdsen-operations/blob/master/conf/ldds/config.yml), which must be done once the repo is created.

**Comment by jordanpadams** [comment]
@c-suh maybe let's update our procedure to create the repo if it does not exist? we actually have the process here: https://pds-data-dictionaries.github.io/development/ldd-create.html#creating-new-ldd-repository-admin-only

**Comment by acraugh** [comment]
If you want users to create the repo first, then the docs need to say that.
I'm happy to try creating it myself - I was just waiting for some sort of
official notification that the namespace had, in fact, been reserved -
which I never got.

-Anne.

**Comment by jordanpadams** [comment]
@acraugh i think it makes a lot of sense for EN to create the repo as part of our procedure. I agree that the namespace should be created first, and then the repo next. we will let you know when the new repo is ready

**Comment by acraugh** [comment]
Okey-doke - thanks!

-Anne.
