### ISSUE TITLE
As an operator, I want to be able to convert from XML to RDF using the PDS4 Information Model

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds4-information-model#387]
## Motivation
...so that I can ingest the RDF for PDS4 products into a graph DB

## Acceptance Criteria
**Given** a PDS4 XML product
**When I perform** execution of this new TBD utility
**Then I expect** have a valid RDF returned that is directly tied to logical identifiers and data types in the PDS4 Information Model

## Engineering Details

Initial steps:
- [x] create a new Jupyter Notebook in the Neptune workbench
- [x] try out a basic translation from XML to RDF

See comments for follow-on tasks.

**Comment by tloubrieu-jpl** [comment]
We can start to work with this XML PDS4 label : https://pds-imaging.jpl.nasa.gov/data/nsyt/insight_cameras/bundle_9.0.xml

**Comment by tloubrieu-jpl** [comment]
## From input:

<Product_Bundle xmlns="http://pds.nasa.gov/pds4/pds/v1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://pds.nasa.gov/pds4/pds/v1 https://pds.nasa.gov/pds4/pds/v1/PDS4_PDS_1B10.xsd">
  <Identification_Area>
  <logical_identifier>urn:nasa:pds:insight_cameras</logical_identifier>
  <version_id>9.0</version_id>
  <title>InSight Cameras Bundle</title>
  <information_model_version>1.11.1.0</information_model_version>
  <product_class>Product_Bundle</product_class>



## With functions: 


def get_im_object_id(label):
    return id # pds4:urn:nasa:pds:0001_nasa_pds_1:pds:product_components:pds:identification_area::1.0

import uuid

def create_unique_id():
  uuid.uuid4()

## Generate something like:

8d49da8d-f664-42ba-a9a9-d3af87e8bd18 rdf:type pds4:urn:nasa:pds:0001_nasa_pds_1:pds:product:pds:product_bundle::1.0
    pds4:identification_area 3d87e76a-67d1-4320-94db-5c4d10643fe5; # not sure if it is possible to create that from the IM available in turtle file yet

3d87e76a-67d1-4320-94db-5c4d10643fe5 rdf:type pds4:urn:nasa:pds:0001_nasa_pds_1:pds:product_components:pds:identification_area::1.0
    pds4:logical_identifier urn:nasa:pds:insight_cameras

**Comment by jordanpadams** [comment]
@tloubrieu-jpl per above, I believe you meant `pds4:urn:nasa:pds:product:product_bundle::1.0` not `pds4:urn:nasa:pds:0001_nasa_pds_1:pds:product:pds:product_bundle::1.0`? the former is the UUID in the TTL file, while the latter seems like it may be some combination of TTL and the JSON object file?

**Comment by tloubrieu-jpl** [comment]
Hi @jordanpadams ,

I took the bundle concept id from this rdf definition in the latest turtle file that @jshughes sent us:

```
pds4:urn:nasa:pds:0001_nasa_pds_1:pds:product:pds:product_bundle::1.0 rdf:type rdfs:Class;
  rdfs:label "Product_Bundle";
  pds4:subClassOf pds4:urn:nasa:pds:0001_nasa_pds_1:all:user:pds:product::1.0;
  rdfs:comment "A Product_Bundle is an aggregate product and has a table of references to one or more collections.".
```

You are right that look at bit weird. 
I am thinking Tishauna should still work to get the rdf object id and may be Steve can update the turtle file with a clean urn.

Here is the turtle file I was looking at:
[PDS4_PDS_RDFTTL_1H00.ttl.zip](https://github.com/NASA-PDS/pds4-information-model/files/6933138/PDS4_PDS_RDFTTL_1H00.ttl.zip)

**Comment by jshughes** [comment]
Hi @jordanpadams , @TWilson2017,  @tloubrieu-jpl

The identifier pds4:urn:nasa:pds:0001_nasa_pds_1:pds:product:pds:product_bundle::1.0 results from the following.

pds4 - rdf prefix for PDS4
urn:nasa:pds: - LID prefix for all PDS4 LIDs
0001_nasa_pds_1 - The registration authority identifier.
pds - namespace id (xml prefix) for the class
product - The parent class name
pds - the  namespace id for the class
product_bundle - the name of the class.
1.0 - The version identifier

The string :0001_nasa_pds_1:pds:product:pds:product_bundle is a typical internal unique identifier for a class in the Information Model database.

The parent class "product" could be omitted if desired.

**Comment by tloubrieu-jpl** [comment]
Thanks @jshughes I don't have an opinion on that.

just one question, is the pds: namespace sonwhat redundant with the pds4: urn prefix ? Or can we have something different than 'pds:' ?

**Comment by jshughes** [comment]
>  Or can we have something different than 'pds:' ?

There are many namespaces, one for each local data dictionary. The number is now about 84. The use of two namespaces is required since the namespace of an attribute can be different than the namespace of its class.

**Comment by jordanpadams** [comment]
@TWilson2017 please delete the TTL file you have on your file system and download the one above.

**Comment by jordanpadams** [comment]
This initial prototype is completed and is available in AWS Neptune Workbench
