### ISSUE TITLE
[namespace-registry] add new namespace "<kpds>"

### ISSUE THREAD

**Issue by kplopds4** [NASA-PDS/pds4-information-model#402]
* **Namespace ID Requested:** kpds
* **Discipline or Mission LDD?** International dictionary for an archiving authority
* **Steward Organization Name:** Korea Aerospace Research Institute
* **LDD Steward Name:** KPDS (KARI)
* **LDD Steward Email:** jryim at kari.re.kr
* **LDD Description:** Namespace for the KPDS (KARI) dictionary.
* **Rationale for creation of new LDD:** Required for the generation of PDS4 Bundles for KARI’s Korea Pathfinder Lunar Orbiter.
---

**Engineering Details**
- [ ] @jshughes update namespace registry

**Comment by kplopds4** [comment]
I created this kpds with "get started" button but today I found it was duplicated with other one already created on August 18, from Joo Hyeon KIM under the same namespace. Would you please delete this namespace-registry? Thanks a lot.

**Comment by jshughes** [comment]
I concur, this is a duplicate.
