### ISSUE TITLE
CCB-329 - Broaden Definition of Attribute aperture

### ISSUE THREAD

**Issue by jshughes** [NASA-PDS/pds4-information-model#403]
https://pds-jira.jpl.nasa.gov/browse/CCB-329

CCB-329 - The aperture attribute is defined for optical instruments with circular light collecting openings. Telescopes at radio wavelengths are not necessarily circular and may be arrays. Broadening the definition will make the attribute more useful at all wavelengths. 

Change definition of aperture to: "The aperture attribute provides a measure of the effective collecting area of the telescope -- its diameter (if single and circular) or its equivalent diameter (if non-circular and/or an array)."

For purposes of this definition, aperture efficiency is assumed to be 100 percent.

**Comment by jordanpadams** [comment]
@jshughes is this planned for this build? or is this for B12.1?
