### ISSUE TITLE
CCB-342: NASA, CODMAC, and PDS Processing Levels for Science Data Sets

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds4-information-model#415]
Discussion via email thread started, but need to develop some sort of table comparing PDS4 processing levels with PDS3 terminology. Additionally, we may take this to the next level adding a comparison to CODMAC and NASA Processing Levels.

https://pds-jira.jpl.nasa.gov/browse/CCB-342

**Comment by jordanpadams** [comment]
@jshughes @rsjoyner any idea where we wound up with this? has this been brought to the DDWG for review?

**Comment by jordanpadams** [comment]
📆 November status: On schedule

**Comment by jshughes** [comment]
The following SCR has been submitted and is being discussed. 
CCB-342 - NASA, CODMAC, and PDS Processing Levels for Science Data Sets
https://pds-jira.jpl.nasa.gov/browse/CCB-342

**Comment by jordanpadams** [comment]
📆 December status: In progress. Completion date dependent upon DDWG deliverable.

**Comment by jordanpadams** [comment]
📆 January status: waiting on receiveable from DDWG. out of our hands, so no impact on B12.1

**Comment by jordanpadams** [comment]
Initial recommendation: [ProcessingLevelsMapping_220202b.docx](https://github.com/NASA-PDS/pds4-information-model/files/7998639/ProcessingLevelsMapping_220202b.docx)

[PolicyOnProcessingLevels03112013.docx](https://github.com/NASA-PDS/pds4-information-model/files/7998640/PolicyOnProcessingLevels03112013.docx)

**Comment by jordanpadams** [comment]
@jshughes is this done now and part of the build? do we have something EN needs to do to get this posted somewhere online?

**Comment by jshughes** [comment]
@jordanpadams Yes, this is done and part of the build. The plan was to have the DDWG review it and vote to recommend. Since this happened, it is now a formal "Recommendation". 

Yes, the EN should post this. Since it is not a standards but simply a recommendation, it should be available with the standards reference and the DPH for data providers to find and retrieve.

**Comment by jordanpadams** [comment]
copy. thanks @jshughes created a ticket to get it added to the Document web page: https://github.com/NASA-PDS/portal-tasks/issues/20
