### ISSUE TITLE
Inconsistent naming of JSON schema files

### ISSUE THREAD

**Issue by tdddblog** [NASA-PDS/pds4-information-model#418]
## 🐛 Describe the bug
Many non-PDS schemas (I didn't check all of them) have the same file name for both XSD and JSON files, for example, `PDS4_CART_1G00_1950.xsd` and `PDS4_CART_1G00_1950.JSON`, but for PDS schema, file names are different: `PDS4_PDS_1G00.xsd` and `PDS4_PDS_JSON_1G00.JSON`.
It makes it more difficult / requires special logic to find JSON schema location from corresponding XSD, e.g., `http://pds.nasa.gov/pds4/pds/v1/PDS4_PDS_1500.xsd`

This issue is related to https://github.com/NASA-PDS/pds-registry-mgr-elastic/issues/31 I'm working on.

## 📜 To Reproduce
1. Go to https://pds.nasa.gov/datastandards/dictionaries/index-1.16.0.0.shtml
2. Check PDS schema files: `PDS4_PDS_1G00.xsd` and `PDS4_PDS_JSON_1G00.JSON`
3.  Check non-PDS schema files, e.g., `PDS4_CART_1G00_1950.xsd`, `PDS4_CART_1G00_1950.JSON`

## 🕵️ Expected behavior
Schema files should have the same name. Only file extension should be different (xsd, JSON, etc.)

## 📚 Version of Software Used
https://pds.nasa.gov/datastandards/dictionaries/index-1.16.0.0.shtml

**Comment by jordanpadams** [comment]
@jshughes can we update this for all future releases of the IM?

@c-suh can we go out to the file system and copy all the `PDS4_PDS_JSON_***.JSON` files to their `PDS4_PDS_1G00.JSON` equivalent?

**Comment by tloubrieu-jpl** [comment]
@jordanpadams will add a comment on this ticket

**Comment by c-suh** [comment]
@jordanpadams, is there a plan for this? I believe @jshughes started renaming the existing files - should he continue or desist?

**Comment by jordanpadams** [comment]
@c-suh @jshughes is working on renaming all future files. for past files, lets go out to the file system and copy all the PDS4_PDS_JSON_***.JSON files to their PDS4_PDS_1G00.JSON equivalent for online access?

**Comment by jordanpadams** [comment]
As a note on this ticket, went out and duplicated / renamed all the existing JSON files.

**Comment by jordanpadams** [comment]
@tdddblog ☝️ per our discussion at yesterday's breakout. e.g. https://pds.nasa.gov/pds4/pds/v1/PDS4_PDS_1H00.JSON

**Comment by rchenatjpl** [comment]
@jshughes @jordanpadams @tdddblog So what does lddtool create now?
  PDS4_PDS_1I00.JSON or
  PDS4_PDS_JSON_1I00.JSON
Is there a PDS4_PDS_IngestLDD.xml we can test this with? If so, where? Thanks

**Comment by jshughes** [comment]
@rchenatjpl LDDTool now creates PDS4_PDS_1I00.JSON. Any Ingest_LDD could be used for testing. You would need a prior version of LDDTool to generate a file name like PDS4_PDS_JSON_1I00.JSON.
