### ISSUE TITLE
Schema URL in PDS Label XMLs is not available on pds.nasa.gov web site.

### ISSUE THREAD

**Issue by tdddblog** [NASA-PDS/pds4-information-model#419]
## 🐛 Describe the bug
Cassini labels use upper case for XSD file name:
`https://pds.nasa.gov/pds4/mission/cassini/v1/PDS4_CASSINI_1B00_1300.xsd`
but `pds.nasa.gov` site has file in camel case:
`https://pds.nasa.gov/pds4/mission/cassini/v1/PDS4_Cassini_1B00_1300.xsd`
**Possible solutions**: 
(1) make the URL case-insensitive.
(2) covert the URL to lower case, at least for JSON schemas. The downside is that applications / clients should know they have to convert the URL to lower case.

## 📜 To Reproduce
- Open `https://pds-rings.seti.org/pds4/bundles/cassini_vims_cruise/data_raw/129xxxxxxx/12946xxxxx/1294638283.xml` (It looks like current version of the label is invalid / malformed)
- Check schema location URL: `https://pds.nasa.gov/pds4/mission/cassini/v1/PDS4_CASSINI_1B00_1300.xsd`
- The schema is not available at that URL.

## 🕵️ Expected behavior
PDS labels should have valid schema URLs or `pds.nasa.gov` site should ignore case.

## 🖥 System Info

---

**Comment by jordanpadams** [comment]
@tdddblog let's toss that example. if the schema is not online, the data is invalid and should not be online either.

let's raise an error like

> Schema not found 'url'. Verify schema has been released or manually update using '--update-schema' flag.
