### ISSUE TITLE
Missing JSON LDDs (alt & particle)

### ISSUE THREAD

**Issue by tdddblog** [NASA-PDS/pds4-information-model#424]
## 🐛 Describe the bug
JSON versions of LDDs are not available for
- http://pds.nasa.gov/pds4/alt/v1/PDS4_ALT_1000.xsd
- http://pds.nasa.gov/pds4/particle/v1/PDS4_PARTICLE_1100.xsd

These LDDs are used by recent 2021 MAVEN labels, for example,
https://pds-ppi.igpp.ucla.edu/data/maven-swea-calibrated/data/arc_3d/2021/01/mvn_swe_l2_arc3d_20210102_v04_r03.xml

**Comment by jordanpadams** [comment]
These are completed. Awaiting the JSON files to be posted online: https://github.com/NASA-PDS/operations/issues/201
