### ISSUE TITLE
remaining code cleanup / refactoring

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds4-information-model#440]
Finish testing the Refactoring of Class information into the Protege database.

**Comment by jordanpadams** [comment]
@jshughes while doing this, can we also remove this from future file outputs:

```
  <!--   file:/path/to/ingest_ldd -->
```

this type of information is not exactly "archival" :-), and actually a very minor potential IT security concern it could show the absolute path of an online server

**Comment by jshughes** [comment]
@jordanpadams Yes, these lines can easily be removed from the Dictionary Stack listing. It is now planned for the next refactoring update.

**Comment by jordanpadams** [comment]
@jshughes any more work going into this? will this be included in the updates you are making for the SCRs? or do we call this good for this build?

**Comment by jordanpadams** [comment]
@jshughes per yesterday's meeting, do we think we are good to go on the refactoring for this build?

**Comment by jordanpadams** [comment]
thanks. for each of these updates, let's create new tickets for the specific things you would like to accomplish. even if they are grouped together, we want to identify the distinct upgrades we are making to the outputs.

that being said, it does not sounds like these are blockers on the build. so i would like to close out this effort for B13.0, and we can work these enhancements for B13.1.
