### ISSUE TITLE
XML Schema files generated by LDDTool should not write the source file names in the header

### ISSUE THREAD

**Issue by jshughes** [NASA-PDS/pds4-information-model#444]
Remove the following from future XSD file outputs generated by LDDTool

  

this type of information is not exactly "archival" :-), and actually a very minor potential IT security concern it could show the absolute path of an online server

**Comment by rchenatjpl** [comment]
@jshughes What was being listed in the .xsd files - the ingest_*.xml? If that's not what's being referred to, please tell me what I should be looking for. Thanks

**Comment by rchenatjpl** [comment]
I do see the .xml file listed in a .xsd file I just created - is that ok?
  <xs:annotation>
    <xs:documentation>
    The InSight mission dictionary contains classes and attributes specific to
    the InSight mission and its instruments.
    InSight version 1.9.0.0 last updated 2021-06-08
    PDS Build 1.15.0.0
    LDDTool version 13.0.2
    Built with LDDTool -plJ -V 1F00 PDS4_INSIGHT_IngestLDD.xml
    </xs:documentation>
  </xs:annotation>

**Comment by jshughes** [comment]
@rchenatjpl Before the change LDDTool generated the .xsd with the following lines (examples) in the commented section at the beginning of the file. These lines are no longer written to the file.

Examples:
1. file:PDS4_CART_IngestLDD.xml 
2. file:PDS4_DISP_IngestLDD.xml     

Original Source.
<?xml version="1.0" encoding="UTF-8"?>

**Comment by tloubrieu-jpl** [comment]
See https://github.com/pds-data-dictionaries/ldd-cart for input dictionnary

**Comment by jshughes** [comment]
The lines below are examples of the lines that are no longer being written as per the request.

    file:PDS4_CART_IngestLDD.xml
    file:PDS4_DISP_IngestLDD.xml

**Comment by jordanpadams** [comment]
@rchenatjpl don't worry about testing this. super trivial update...
