### ISSUE TITLE
CCB-344:  Add data_to_partially_processed_product to reference types for Internal_Reference

### ISSUE THREAD

**Issue by jshughes** [NASA-PDS/pds4-information-model#446]
https://pds-jira.jpl.nasa.gov/browse/CCB-344

The request is to add the permissible values “data_to_partially_processed_product” to the attribute <Product_Observational.Internal_Reference.reference_type>. This addition will allow data products to be related to partially processed data products.

**Comment by jpl-jengelke** [comment]
[testdata.zip](https://github.com/NASA-PDS/pds4-information-model/files/8674001/testdata.zip)
a
