### ISSUE TITLE
CCB-343: Revise Product_Metadata_Supplemental

### ISSUE THREAD

**Issue by jshughes** [NASA-PDS/pds4-information-model#448]
https://pds-jira.jpl.nasa.gov/browse/CCB-343

CCB-343 - Revise Product_Metadata_Supplemental  	
				
The request is to remove the restriction that Product_Metadata_Supplemental may only be associated with one collection. Removing this restriction requires changing text in the description of the class in the IM and associated text in the Standards Reference. This change will improve the effective use of Product_Metadata_Supplemental.

**Comment by rchenatjpl** [comment]
@jshughes @jpl-jengelke Steve, is this right? This only changed documentation: 1) the Standards Reference, and 2) the description field of Product_Metadata_Supplemental in the .xsd
Thanks

**Comment by jpl-jengelke** [comment]
Where is the latest IM Spec that was used to prepare the changes located? Where is the Product Metadata Supplemental? Is this from 1.16.0->1.17.0 (or something) so it can be tested against older specs?

**Comment by jordanpadams** [comment]
@jpl-jengelke we will have a draft out to the be reviewed in a bit. that being said, there is a commit for this.

@jshughes what code or documentation updates were intended as part of this SCR?

**Comment by jordanpadams** [comment]
@jpl-jengelke so looking at this again, those code changes are for the IM Spec. the new IM Spec is posted here: https://pds.nasa.gov/datastandards/documents/im/v1/index_1I00.html

it is just not officially linked from the website just yet until we complete the release.

**Comment by jshughes** [comment]
@jpl-jengelke It might help a little to know that if the change results from an approved Standards Change Request (SCR), aka (CCB-nnn) then it is best to first read the "Requested Changes" section of the SCR. During the technical assessment phase, we try to ensure that the change is explained precisely as possible in this section. In fact we only implement what is stated explicitly in this section.  (There are few exceptions.)

**Comment by jpl-jengelke** [comment]
To collate information in a single location, the CCB-343 "Requested Changes" are:
`Add "data_to_partially_processed_product" to the list of valid values for Internal_Reference/reference_type.`
