### ISSUE TITLE
CCB-335: Inventory Specification Allows Too Many Delimiters

### ISSUE THREAD

**Issue by jshughes** [NASA-PDS/pds4-information-model#453]
https://pds-jira.jpl.nasa.gov/browse/CCB-335

The request is to add schematron rules to limit the attribute <Inventory.field_delimiter> to one and only one value "Comma" and add additional related constraints. This change will make the IM consistent with the Standards Reference where it states that "Records in the Inventory table [have] two fields, delimited by a single comma."

**Comment by jpl-jengelke** [comment]
[testdata.zip](https://github.com/NASA-PDS/pds4-information-model/files/8674004/testdata.zip)
