### ISSUE TITLE
PDS4_PDS_1I00.sch has two bugs regarding CCB-339

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds4-information-model#455]
Refs #443

@jshughes: PDS4_PDS_1I00.sch has two bugs regarding this. 
1. Line 528 is
  sch:rule context="DD_Value_Domain/pds:unit_of_measure_type" role="warning"
but should be
  sch:rule context="pds:DD_Value_Domain/pds:unit_of_measure_type" role="warning"
2. Lines 532,534,588,590 are missing 'Units_of_Power'

The attached badtype.xml's line 30 has unit_of_measure_type = thisshouldnotpassbutdoes, but it passes validate due to the first bug. If you fix that bug but not the second, the attached shouldpass.xml fails validate because lines 30 and 43 have unit_of_measure_type = Units_of_Power
[Archive.zip](https://github.com/NASA-PDS/pds4-information-model/files/8308709/Archive.zip)

_Originally posted by @rchenatjpl in https://github.com/NASA-PDS/pds4-information-model/issues/443#issuecomment-1072950590_

**Comment by jordanpadams** [comment]
@rchenatjpl as a reminder, I know it's a pain, but if you come across a bug when testing, if you could create a new I&T Bug that would be great! I automatically tags things properly and tracks things so we make sure we don't lose these issues.

**Comment by jordanpadams** [comment]
Create a new ticket here https://github.com/NASA-PDS/pds4-information-model/issues/455

**Comment by rchenatjpl** [comment]
sorry, my memory is so bad, and I don't do this often. Also, this (creating new tickets) is one of the things that made testing tougher, tracking down the input files and maybe the logic of an issue.

**Comment by jordanpadams** [comment]
@rchenatjpl no worries! Takes some time to get used to

**Comment by tloubrieu-jpl** [comment]
@jshughes let us know when you can make progress on this ticket. Thanks

**Comment by jshughes** [comment]
@tloubrieu-jpl @viviant The changes had been made but it seems the pull request had not been made. I just did the pull request.

**Comment by viviant100** [comment]
thank you @jshughes

**Comment by jordanpadams** [comment]
resolved per PR #461
