### ISSUE TITLE
As a developer I want to have the PDS4 Information Model expressed in the RDF/OWL/TTL format. 

### ISSUE THREAD

**Issue by jshughes** [NASA-PDS/pds4-information-model#458]
## 💪 Motivation
...so that I can allow researchers and developers to use semantic technology such as the sparql query language and triple and graph database engines to analyze the the model.

## ⚖️ Acceptance Criteria
**Given** 
**When I perform** 
**Then I expect** 

## Engineering Details
One current task involves "mashing" together the PDS4 IM with the IKG ontology to determine overlaps and identify common concepts that can be harmonized.

**Comment by jordanpadams** [comment]
@jshughes FYI, I created a couple sub-tickets for this requirement:
- https://github.com/nasa-pds/pds4-information-model/issues/466
- #467

**Comment by jshughes** [comment]
This RDF/OWL/TTL formatted file has been successfully used in an IKG project as per Ann Bernath. She will be scheduling a demo soon. Until additional requirements are clear, I would like to close this issue.

IMTool is currently able to generate another RDF/OWL file in a more general format and which contains much more of the information in the IM. I plan to open another issue to add a flag for this legacy RDF/OWL file. Note this file was used previous by some of our interns and has been shared with an SMD project gathering semantic information from each of the archives.

**Comment by miguelp1986** [comment]
@jordanpadams the subtasks are labeled as i&t.skip. Should this epic be treated the same as well?

**Comment by jordanpadams** [comment]
@miguelp1986 yes
