### ISSUE TITLE
LDDTool 14 is not generating against past versions of the IM correctly

### ISSUE THREAD

**Issue by jstone-psi** [NASA-PDS/pds4-information-model#463]
## 🐛 Describe the bug
When running lddtool 14 with the -V flag and specifiying an old version of the IM, such as 1E00 or 1F00, the tool generates hundreds of errors. This does not happen when generating without the -V flag, and does not seem to happen with past versions of LDDTool. Interestingly, the tool still generates all of the schema files that it is supposed to, however, the errors that it emits are preventing GitHub actions from running (https://github.com/NASA-PDS/gh-action-pds4-ldd/issues/2)

## 📜 To Reproduce
1. Run lddtool with the -V 1E00 flag on an ldd.
Example: `~/bin/lddtool-14.0.0/bin/lddtool -lpJ -V 1E00 PDS4_DISP_IngestLDD.xml`
2. See error

## 🕵️ Expected behavior
The tool should not be generating any errors when generating its artifacts.

## 📚 Version of Software Used
14.0.0

## 🩺 Test Data / Additional context
This happens with at least the survey and disp dictionaries:
[PDS4_DISP_IngestLDD.xml.txt](https://github.com/NASA-PDS/pds4-information-model/files/8484152/PDS4_DISP_IngestLDD.xml.txt)
[PDS4_SURVEY_IngestLDD.xml.txt](https://github.com/NASA-PDS/pds4-information-model/files/8484154/PDS4_SURVEY_IngestLDD.xml.txt)

Here are some sample outputs:

[lddtool_result_1E00.txt](https://github.com/NASA-PDS/pds4-information-model/files/8484158/lddtool_result_1E00.txt)
[lddtool_result_1F00.txt](https://github.com/NASA-PDS/pds4-information-model/files/8484159/lddtool_result_1F00.txt)
[lddtool_result_1G00.txt](https://github.com/NASA-PDS/pds4-information-model/files/8484160/lddtool_result_1G00.txt)

## 🖥 System Info
 - OS: MacOS , OpenJDK 2022-03-22
 - Version MacOS 11.6.5

---

**Comment by jordanpadams** [comment]
@jshughes can we add this as a high-priority bug fix?

**Comment by jordanpadams** [comment]
@tloubrieu-jpl removing release 14.0.0 for the IM so the Github actions for LDD builds will still work

**Comment by tloubrieu-jpl** [comment]
thanks @jordanpadams
