### ISSUE TITLE
Add flags to support generation of TTL/OWL files

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds4-information-model#467]
## 💡 Description

similar to the flag to product JSON, we should have flags to produce these other files

**Comment by tloubrieu-jpl** [comment]
@jordanpadams should @jshughes work on that ? That would allow to close the EPIC https://github.com/nasa-pds/pds4-information-model/issues/458

**Comment by jordanpadams** [comment]
@tloubrieu-jpl sure let's add that to the top of the stack

**Comment by jordanpadams** [comment]
@jshughes you think you can get to this in the next 3 weeks?
