### ISSUE TITLE
The IM failed to set the cardinality spec strictly for the ‘Inventory.Uniformly_Sampled’ attribute

### ISSUE THREAD

**Issue by viviant100** [NASA-PDS/pds4-information-model#477]
## 🐛 Describe the bug identified during I&T

The IM failed to set the cardinality spec strictly for the ‘Inventory.Uniformly_Sampled’ attribute, which is required in CCB-335 to disallow usage (see "Requested Changes" section #4 Prohibit inclusion of Inventory.Uniformly_Sampled (for example, by setting its cardinality to 0..0)

This was found during testing of [pds4-information-model#453](https://github.com/NASA-PDS/pds4-information-model/issues/453) ticket.

## 🔁 : Related issues
[pds4-information-model#453](https://github.com/NASA-PDS/pds4-information-model/issues/453)

---

### 🖥 System Info

---

**Comment by viviant100** [comment]
@jpl-jengelke please fill in the rest to complete the ticket.  Thanks.

**Comment by jpl-jengelke** [comment]
**** DUPLICATE ****

Please close this ticket as it is a duplicate of #478
