### ISSUE TITLE
Data Provider’s Handbook v1.18.0 is missing the Appendix F text requested in the CCB-340

### ISSUE THREAD

**Issue by jpl-jengelke** [NASA-PDS/pds4-information-model#480]
## 🐛 Describe the bug identified during I&T
A text paragraph is strictly declared in CCB-340 which states it should go at the end of Appendix F in the Data Provider's Handbook v1.18.0. The paragraph is not in the prepared version of the DPH.

## 🥼 Related Test Case(s)
[IM.12](https://pds-engineering.jpl.nasa.gov/sites/default/files/documents/Build%20Deliverables/Build%2012.1%20I%26T%20Deliverables/Release%20Build%2012.1%20Test%20Plan.v6.20220407.pdf)

## 🔁 : Related issues
[pds4-information-model#450](https://github.com/NASA-PDS/pds4-information-model/issues/450)
[CCB-340](https://pds-jira.jpl.nasa.gov/browse/CCB-340)

---

### 📜 To Reproduce
1. Open the unreleased PDH PDF, entitled _PDS4_DPH_1.18.0_20220503.pdf_
2. Go to Appendix F in the document.
3. Note that the requested paragraph is nowhere in the appendix.

### 🕵️ Expected behavior
The precise paragraph specified is added into Appendix F at the end.

### 📚 Version of Software Used
1.18.0 (model-ontology 14.0.1, release `I`)

### 🩺 Test Data / Additional context
PDH PDF, entitled _PDS4_DPH_1.18.0_20220503.pdf_

###  🏞Screenshots
(See unreleased PDF)

### 🖥 System Info

---

**Comment by viviant100** [comment]
This has been addressed.
