### ISSUE TITLE
CCB-348: Add Units_of_Mass_Density as a unit of measure

### ISSUE THREAD

**Issue by jshughes** [NASA-PDS/pds4-information-model#499]
https://pds-jira.jpl.nasa.gov/browse/CCB-348

The unit_of_measure_type should include the class Units_of_Mass_Density, which would contain the following attributes:

1. specified_unit_id in Units_of_Mass_Density
The specified_unit_id attribute provides the unit chosen for maximum_value, minimum_value, and permissible_value.

Type: UTF8_Short_String_Collapsed
Class Name: Units_of_Mass_Density
Minimum Characters: 1
Maximum Characters: 255
Nillable: false
Attribute Concept: ID
Conceptual Domain: Short_String
Steward: pds
Namespace Id: pds

Value:
- kg/m**3 - Units_of_Mass_Density maximum, minimum, and permissible values are given in the unit kilograms per cubic meter.

2. type in Units_of_Mass_Density
The type attribute classifies units of density according to the quantity being measured (density).

Type: ASCII_Short_String_Collapsed
Class Name: Units_of_Mass_Density
Minimum Characters: 1
Maximum Characters: 255
Nillable: false
Attribute Concept: Type
Conceptual Domain: Short_String
Steward: pds
Namespace Id: pds

Value:
- Density - Units_of_Mass_Density is classified as being of type of Mass Density and also known as Volumetric Mass Density. Density is the relationship between the mass of the substance and the volume it takes up.

3. unit_id in Units_of_Mass_Density
The unit_id attribute provides a character or character string which serves as an abbreviation for, or symbol representing, a unit of measure.

Type: UTF8_Short_String_Collapsed
Class Name: Units_of_Mass_Density
Minimum Characters: 1
Maximum Characters: 255
Nillable: false
Attribute Concept: ID
Conceptual Domain: Short_String
Steward: pds
Namespace Id: pds

Values:
- kg/m**3 - The abbreviated unit for kilograms per cubic meter in Units_of_Mass_Density
- g/cm**3 - The abbreviated unit for grams per cubic centimeter in Units_of_Mass_Density

**Comment by jpl-jengelke** [comment]
@jshughes: Is there a way to test this besides stare and compare at old/new schemas?

**Comment by rchenatjpl** [comment]
@jpl-jengelke 1) Part 1 is the eyeballing, where you'd look at the new .xsd AND the .sch to check that every place something like "Units_of_Time" shows up, "Units_of_Mass_Density" also shows up. 2) The harder part is showing that a) lddtool will create an LDD that includes "Units_of_Mass_Density", and b) the new LDD correctly validates a label that has a type based on Units_of_Mass_Density.
Do you have my testing from 1I00? If so, ccb339 should be a decent model. It has a good lddinput file, a bad one, then a good label and a bad label that you can validate against the good LDD.

**Comment by jpl-jengelke** [comment]
[testdata.zip](https://github.com/NASA-PDS/pds4-information-model/files/9945216/testdata.zip)

**Comment by jshughes** [comment]
Another thought is that the Discipline Model Standardization Project (DMSP) guidelines now require that the LDD developer needs to include regression test cases for a new LDD. Similarly, it seems reasonable to have the requestor for a new Unit of measure to provide the regression tests. We can take this idea to the DDWG chair for consideration. In any case, we should be able to request the creator of any approved SCR  to provide the tests cases, after the fact.

**Comment by jordanpadams** [comment]
@jshughes can you look at this? this is a high priority if it does not actually work correctly

**Comment by jordanpadams** [comment]
@tloubrieu-jpl can you help me understand how this requirement has not been fixed? I see there was an issue with validate, but that has nothing to do with this ticket. I think I am closing this as complete
