### ISSUE TITLE
hyb2 has incorrect namespace for IM v1.14

### ISSUE THREAD

**Issue by c-suh** [NASA-PDS/pds4-information-model#506]
## 🐛 Describe the bug
@neese generated dictionary files with IM v1.14 (because of ONC and LIDAR bundles), but the LID starts with `urn:nasa:gov` instead of `urn:jaxa:darts`. (This was not an issue when run with IM v1.18.) More details at [PDS4_HYB2_1E00_1200.txt](https://github.com/pds-data-dictionaries/ldd-hyb2/blob/main/build/development/9af1a7d10b8bfcdce866bdc8d6550dd3049aa77f/1.14.0.0/PDS4_HYB2_1E00_1200.txt) and [PDS4_HYB2_1E00_1200.xml](https://github.com/pds-data-dictionaries/ldd-hyb2/blob/main/build/development/9af1a7d10b8bfcdce866bdc8d6550dd3049aa77f/1.14.0.0/PDS4_HYB2_1E00_1200.xml).
Note: this is a blocker to the Hyb2 LDD being ingested in the next build.

## 📜 To Reproduce
1. Follow steps in https://pds-data-dictionaries.github.io/development/ldd-how-to.html#trigger-ldd-build.
2. According to https://pds-data-dictionaries.github.io/development/ldd-how-to.html#generate-a-ldd-with-a-specific-pds4-version, run LDDTool with `-V 1E00`.
3. See dictionary files.

## 🕵️ Expected behavior
PDS4_HYB2_1E00_1200 dictionary files are generated with LID(s) which start with `urn:jaxa:darts`.

## 📚 Version of Software Used
N/A (GitHub Action pulls latest version of LDDTool). 

## 🩺 Test Data / Additional context
- RChen had a similar issue, described [here](https://github.com/NASA-PDS/pds4-information-model/issues/267#issuecomment-816998024), which @jshughes addressed in [this PR](https://github.com/NASA-PDS/pds4-information-model/pull/334).
- I am not wholly familiar with how the LDDTool works, but does this have anything to do with the absence of hyb2 in [1E00's config.properties](https://github.com/NASA-PDS/pds4-information-model/blob/main/model-ontology/src/ontology/Data/1E00/config.properties)?
- relevant [GitHub Action](https://github.com/pds-data-dictionaries/ldd-hyb2/actions/runs/3129386275/jobs/5078414593).

## 🖥 System Info

---

**Comment by jordanpadams** [comment]
@c-suh this looks like a new bug for @jshughes to fix.

@jshughes it appears we weren't just supposed to change the schema location, but also the LID prefix.

**Comment by c-suh** [comment]
@jshughes, after you merged the fix, @neese initiated the LDD Build again for 1E00, but the LID prefix is still being generated as `urn:nasa:pds` rather than `urn:jaxa:darts` ([as seen here](https://github.com/pds-data-dictionaries/ldd-hyb2/blob/main/build/development/97f58592ca44a9a874a589138175c8fbaf23c3bc/1.14.0.0/PDS4_HYB2_1E00_1200.xml)). I found the following in line 146 of the [execution log](https://github.com/pds-data-dictionaries/ldd-hyb2/blob/push-again-after-bug-fix/logs/v1.14.0.0_execution_logs/lddtool_run_log_20220930195846.txt) for the LDDTool:
> WARNING Init:  - Config.Properties Namespace Id Not Found:hyb2

Is there perhaps another file that needs to be updated? Thank you!

**Comment by c-suh** [comment]
@jordanpadams ah, that seems painfully obvious now. @neese, my apologies for jumping the gun with my request that you try again. Would you please try again (again) now?

NOTE: the [ldd-hyb2 repo](https://github.com/pds-data-dictionaries/ldd-hyb2) doesn't have any tagged releases as of yet, and the [1E00 1200 HYB2 files](https://github.com/pds-data-dictionaries/ldd-hyb2/tree/main/build/development/a6580956e064b119e6d87efffe191f9d4757c125/1.14.0.0) do seem to be re-generating with each push. I'm feeling hopeful that this time will work!

**Comment by c-suh** [comment]
Carol reported via email that it worked as intended!

**Comment by neese** [comment]
Thanks all for your help!
