### ISSUE TITLE
LDDTool does not support IM version 1J00

### ISSUE THREAD

**Issue by c-suh** [NASA-PDS/pds4-information-model#512]
## 🐛 Describe the bug
The LDDTool does not support IM Version 1J00

## 📜 To Reproduce
1. Run the LDDTool ([lddtool-14.1.1-bin.zip](https://github.com/NASA-PDS/pds4-information-model/releases/download/v14.1.1/lddtool-14.1.1-bin.zip)) with `-V 1J00`
2. See error, "Invalid argument list"

## 🕵️ Expected behavior
The LDDTool finishes without errors.

## 📚 Version of Software Used
v14.1.1

## 🩺 Test Data / Additional context
- appeared when trying to prep all dictionary LDDs for review and release (https://github.com/NASA-PDS/operations/issues/306)
- details can be found in this [failed "Generate and Validate (1.19.0.0)" job](https://github.com/pds-data-dictionaries/ldd-img/actions/runs/3268095141/jobs/5374104822)
- the details (second screenshot below) says that 1J00 is the default value for -V but isn't actually listed as one of the values

##  🏞Screenshots
From the second link above in Test Data / Additional context:
![Screen Shot 2022-10-18 at 9 15 45 AM](https://user-images.githubusercontent.com/18314609/196486216-7319be26-18b8-41f9-91e2-13f32362b637.png)
![Screen Shot 2022-10-18 at 9 15 25 AM](https://user-images.githubusercontent.com/18314609/196486249-c4c3121b-92eb-42ee-b1f1-8b08ccd2456a.png)

---

**Comment by jordanpadams** [comment]
thanks @c-suh

**Comment by jshughes** [comment]
@jordanpadams , @c-suh
This issue results from a constraint on LDDTool's implementation of the -V option. Currently if you want to run LDDTool with the current version of the IM, (e.g. "1J00"), then you do not use the -V option. The -V option is used only for indicating prior versions of the IM. This logic is consistent with the originally proposed option "-A" (Alternate). If this needs to be changed so that the -V option  can also indicate the current version of the IM, just let me know.

**Comment by jordanpadams** [comment]
@jshughes I feel like when we changed this to `-V`, we changed this functionality to be more consistent with other `-V` functionality throughout our PDS4 system? Either way, if the `-A` functionality was the intent, there has been a bug supporting the expected `-V`.

Moving forward let's treat `-V` as the version setter for LDDTool. If not given, it defaults to the latest (in this case 1J00), but it can take any available value as input, including the latest version (e.g. 1J00)

**Comment by jshughes** [comment]
@jordanpadams , @c-suh

Jordan you are correct. The code was set up to be consistent with other -V functionality. My build instructions were not clear about adding the current IM version to -V option list of choices. I have added the current version to the choice list and updated my build instructions.
