### ISSUE TITLE
Implement Term Mapping Example for EPNCore Attributes

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds4-information-model#545]

**Comment by jordanpadams** [comment]
@jshughes to confirm, has this been completed?

**Comment by jshughes** [comment]
No, I must still add the examples provided by Baptiste and test the results. This should be completed by end of next week.

**Comment by jordanpadams** [comment]
Draft completed and reviewed with Baptiste at IVOA interop
