### ISSUE TITLE
LDDTool is not using the version number of the discipline dictionary to populate <version_id>

### ISSUE THREAD

**Issue by mace-space** [NASA-PDS/pds4-information-model#568]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

When I looked at some discipline dictionary XMLs – for example, https://github.com/pds-data-dictionaries/ldd-spectral/blob/main/build/release/1.19.0.0/PDS4_SP_1J00_1311.xml – the <version_id> is given incorrectly.

### 🕵️ Expected behavior

Instead of <version_id>=1.25, I expect 1.3.1.1

### 🦄 Related requirements

🦄 #xyz

**Comment by jshughes** [comment]
This is not an issue but the question does periodically come up. The <version_id>=1.25 is the version of the product that labels the XML Schema and Schematron files and not the version of the LDD itself. The product, Product_XML_Schema, is generated once per build and each time the version id is bumped up one. So to date, there are 25 versions of Product_XML_Schema.

**Comment by jordanpadams** [comment]
@mace-space ☝️ 

@jshughes so shouldn't that be the version of that specific Product_XML_Schema, e.g. that particular schema product should be version 1.0, no? since we have not regenerated it?

**Comment by jshughes** [comment]
It is reasonable that the first Product_XML_Schema product label created for a particular build should have v1.0. This however will require that the build identifier be included in the logical_identifier. I will look into whether this will have any significant impact.

**Comment by jordanpadams** [comment]
@jshughes I see. 1.25 is the overall PDS4 IM version. I feel like that explicit versioning info should maybe be captured elsewhere in the metadata? do we need a schema LDD or something to maintain that metadata?

**Comment by jshughes** [comment]
The LDDTool config.properties is where this versioning is currently kept. We could create an LDD for the config.properties file and manage it accordingly. -- BTW, at some point I plan to divide the config.properties file into two parts, common properties and LDD properties . Currently it is not always clear how far back through the IM versions a change or addition to the LDD properties needs to be propagated. Having  a single LDD properties file resolves that.
