### ISSUE TITLE
CCB-355: Add Funding_Acknowledgement class to Citation_Information Class

### ISSUE THREAD

**Issue by jshughes** [NASA-PDS/pds4-information-model#611]
https://pds-jira.jpl.nasa.gov/browse/CCB-355

CCB-355 Add Funding_Acknowledgement class to Citation_Information Class

The request is to add the Funding_Acknowledgement class as an optional element within <Identification_Area.Citation_Information>.

The purpose of this Class is to mirror the funding acknowledgement that is found at the end of peer reviewed scientific publications.

**Comment by miguelp1986** [comment]
@jshughes is there a PDS4 Information Model Specification that you can share for me to verify the results?
