### ISSUE TITLE
As a user I want to export the IM in the RDF/OWL format in RDF format

### ISSUE THREAD

**Issue by jshughes** [NASA-PDS/pds4-information-model#620]
### Checked for duplicates

Yes - I've already checked

### 🧑‍🔬 User Persona(s)

Data Engineer

### 💪 Motivation

For users, we previously added the "-O" option to export an TTL/OWL file.  (Issue #467). This export is unique in that the output format is TTL (as opposed to RDF) and expresses the IM's semantics in OWL based on requirements provide by the JPL (Institutional Knowledge Graph) IKG project.

In addition to the TTL/OWL file, there is another export available that produces an RDF/OWL file. This file contain most of the contents of the IM and the output format is RDF. OWL semantic extensions are used where appropriate. Note however that the semantic owl:class is not supported in GraphDB so the semantic rdfs:class is used instead.

### Acceptance Criteria

**Given** 
**When I perform** 
**Then I expect**

**Comment by jshughes** [comment]
The priority was not high. It was just cleanup left over from Issue #467. This legacy RDF/OWL writer is now useful for the EIM project and possibly the PDS. Also I wanted CCB-350 to be the last SCR implemented for this build. I plan to start on CCB-350 tomorrow and expect it to take most of the morning.

[CCB-350](https://pds-jira.jpl.nasa.gov/browse/CCB-350) Adopt more rigorous/stringent rules for date/time strings.

**Comment by jordanpadams** [comment]
@jshughes copy thanks.
