### ISSUE TITLE
Add TermMaps to default output JSON

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds4-information-model#651]
## 💡 Description

Current functionality has `-T` flag to output TermMaps to separate JSON file.

This enhancement will remove the flag, and automatically detect and output the TermMaps as part of the overall LDD output JSON file.

Related Requirements:
- 🦄 #473

**Comment by jordanpadams** [comment]
@jshughes what is the status of this ticket?

**Comment by jshughes** [comment]
Hi Jordan,
Unfortunately nothing was done this week. I plan to make it a priority in the coming week.
Thanks,
Steve

Sent from my iPhone

On Jun 8, 2023, at 6:34 PM, Jordan Padams ***@***.***> wrote:

﻿

@jshughes<https://urldefense.us/v3/__https://github.com/jshughes__;!!PvBDto6Hs4WbVuu7!IdZTL_kaPJSVl3gikuK7kwHd_fWodvr4iUx8miIrAC4133yOKJ2B_-jgozeSKTUdtUv9ZfjTdAy6smFm0CEbZ6zZWPAP0xT7$> what is the status of this ticket?

**Comment by tloubrieu-jpl** [comment]
@jshughes is about 50% done on that.

**Comment by jordanpadams** [comment]
duplicate of #670
