### ISSUE TITLE
[namespace-registry] add new namespace "mgn"

### ISSUE THREAD

**Issue by c-suh** [NASA-PDS/pds4-information-model#664]
Namespace ID Requested: mgn

Associated Namespace Details: https://github.com/NASA-PDS/operations/issues/414

NOTE: for the PR, please use this issue number and not the operations issue number.

**Comment by jordanpadams** [comment]
closed per #669

**Comment by jordanpadams** [comment]
@jsh

**Comment by jordanpadams** [comment]
@jshughes per the original ticket comment, be sure to reference this ticket in the PR in the future. e.g. (closes #664), not the operations ticket @c-suh references in the comment.
