### ISSUE TITLE
CCB-336 Add a License_Information class to the Identification_Area

### ISSUE THREAD

**Issue by jshughes** [NASA-PDS/pds4-information-model#679]
https://pds-jira.jpl.nasa.gov/browse/CCB-336

CCB-336 Add a License_Information class to the Identification_Area 
Add an optional License_Information class to the Identification_Area with this structure: 

<Identification_Area>
    <License_Information> 
        <name></name> 
        <description></description> 
        <Internal_Reference> 
            <reference_type>product_to_license</reference_type>
            <lid_reference></lid_reference>
        </Internal_Reference>
    </License_Information>
</Identification_Area>

**Comment by miguelp1986** [comment]
@jordanpadams @jshughes Is there anything I need to make to sure is in the ingest file in order to get the License_Information to get generated? I'm not seeing it in my output files.

**Comment by jordanpadams** [comment]
@miguelp1986 this is part of the core information model, so I don't think there is an ingest file for this.

to test this, you will need to create a label or 2 with the new PDS4 Information Model version, and verify you can add this new section to the label. See the JIRA ticket for some examples and more information.

**Comment by miguelp1986** [comment]
I got it validating successfully. I was using 1K00 but this new option is in 1L00 only.
