### ISSUE TITLE
Verify LDDTool Processing of the Discipline LDDs matches previous releases

### ISSUE THREAD

**Issue by jshughes** [NASA-PDS/pds4-information-model#686]
The purpose of this test is to ensure that LDDTool successfully processes all the Disciplines LDDs. However, instead of testing toward the end of Integration and Test, the testing of LDDTool will be performed toward the beginning.

Background: Toward the end of each build cycle, all Discipline LDDs are processed and the results are posted to the PDS4 Website. However, if a bug is discovered, then there is typically little time to debug LDDTool. 

Proposed Testing:
1) Identify the current set of Discipline LDDs
2) Run the prior released version of LDDTool and capture the .xsd, .sch, and ,xml files.
3) Run the to-be-released version of LDDTool and perform a DIFF against the output of step 2.
4) Identify any potential problems.

@jordanpadams @tloubrieu-jpl

**Comment by jordanpadams** [comment]
Closing as done

**Comment by tloubrieu-jpl** [comment]
This ticket is not work for the development team but guidelines on how I&T should. But this contains the requirement and how to test them.

**Comment by miguelp1986** [comment]
@jordanpadams @jshughes Did you want us to test all the discipline LDDs or were there specific ones?

**Comment by jordanpadams** [comment]
@miguelp1986 I think just pick one or 2. The more complicated the better.

I would say ldd-cart, ldd-geom, and ldd-img ? @jshughes any others you can think of?

https://github.com/pds-data-dictionaries/
