### ISSUE TITLE
B14.1 Planetary Systems Target Ontology: Rings, Satellites Small Bodies

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds4-information-model#689]

**Comment by jordanpadams** [comment]
📆 December status: LOE task as SCRs come in. On schedule.

**Comment by jordanpadams** [comment]
📆 01/2024 status: LOE task, incrementally building on ontology. On schedule.

**Comment by jordanpadams** [comment]
📆 02/2024 status: LOE task, incrementally building on ontology. On schedule.

**Comment by jordanpadams** [comment]
Closing this task as completed for B14.1

**Comment by matthewtiscareno** [comment]
Will we get to see the finished product in the near future?
