### ISSUE TITLE
Develop first iteration of provenance model

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds4-information-model#692]

**Comment by jshughes** [comment]
The first iteration of the Provenance Model has been completed. An SCR, CCB-367, has been submitted to JIRA for review by the DDWG. The model has been applied to two use cases, the LID Superseded_By and a calibrated Voyager image. The schema and use cases are attached.

[Archive.zip](https://github.com/NASA-PDS/pds4-information-model/files/12883903/Archive.zip)

Note1: #692 and #663 overlap in that the Superseded_By issue is included in the Provenance model as a use case. #663- CCB-367: Superseded_by / Supersedes 

Note2: In JIRA the title of CCB-367 has been changed to "Provenance LDD Using PROV-DM" from "Superseded_by / Supersedes"

**Comment by jordanpadams** [comment]
Status: Final draft uploaded to SCR JIRA.
