### ISSUE TITLE
[vg2] add new namespace "<vg2>"

### ISSUE THREAD

**Issue by jmafi** [NASA-PDS/pds4-information-model#696]
* **Namespace ID Requested:** vg2

* **Associated Namespace Details:** N/A (existing LDD: https://pds.nasa.gov/datastandards/dictionaries/index-missions.shtml#vg2

---

**Engineering Details**
- [ ] @jshughes update namespace registry

**Comment by matthewtiscareno** [comment]
I don't understand what is being requested here.

The `vg1` namespace already exists, but is being deprecated in favor of the unified `vgr` namespace.

**Comment by jordanpadams** [comment]
@matthewtiscareno this was created prior to the process for creating repos/namespaces so it never got added to the "namespace registry" within the IM. So when LDDTool is run, I believe it throws a warning that the namespace has not been registered.

This is just to ensure we don't have namespace collisions in the system
