### ISSUE TITLE
CCB-357: Create Product_External - LID Schematron Rule Update

### ISSUE THREAD

**Issue by jshughes** [NASA-PDS/pds4-information-model#698]
https://pds-jira.jpl.nasa.gov/browse/CCB-357

CCB-357 Create Product_External 
The Schematron Rule for the Product_External LID needed update to allow for non-NASA products. 
The rule expects "urn:xxx:yyy:zzz". I.e. The LID need only to begin with "urn:" but still requires at least four terms. See the DPH for more detailed information.

**Comment by rsjoyner** [comment]
See enclosure for some test cases for the schematron rules.  You might want to expand them....

[Product_External_test_cases_20231012.zip](https://github.com/NASA-PDS/pds4-information-model/files/12885545/Product_External_test_cases_20231012.zip)
