### ISSUE TITLE
Initial Implementation of Cucumber Framework for PDS4 IM Repo

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds4-information-model#701]
## 💡 Description

See https://github.com/NASA-PDS/validate/tree/main/src/test for a start

- #714
- #786
- #787
- #715

**Comment by jordanpadams** [comment]
📆 October status: Start delayed due to work on https://github.com/NASA-PDS/pds4-information-model/issues/663 and DDWG Open Session planned for November 14. Training completed on 11/1. No impact on delivery anticipated.

**Comment by jordanpadams** [comment]
Deferring this to later build. This is an internal developer nice to have. No impact on delivery to customer.

**Comment by jordanpadams** [comment]
📆 December status: In progress. On schedule

**Comment by jordanpadams** [comment]
📆 01/2024 status: In work. On Schedule

**Comment by jordanpadams** [comment]
📆 02/2024 status: Deferring. nice-to-have internal optimization. No impact on build.

**Comment by jordanpadams** [comment]
📆 03/2024 status: Deferring to B15.0. This is an internal operations automation task, so no impact on delivery to I&T.

**Comment by jordanpadams** [comment]
📆 04/2024 status: In work on schedule.

**Comment by miguelp1986** [comment]
@jordanpadams How would you like me to prioritize the issues on this epic?

**Comment by jordanpadams** [comment]
@miguelp1986 just re-ordered.

**Comment by jordanpadams** [comment]
📆 06/2024 status: In work. Delayed an additional 2 sprints as team member was working on I&T activities. Test automation tasks with no impact on overall system.

**Comment by jordanpadams** [comment]
Going to call this good. Initial implementation complete. Need to add the tests into the framework.
