### ISSUE TITLE
Add KARI as a new agency `urn:kari:kpds`

### ISSUE THREAD

**Issue by jshughes** [NASA-PDS/pds4-information-model#709]
Update schematron for the agency urn:kari:kpds (Korean PDS)

The problem associated with urn:kari:kpds is that a new namespace for the Korean PDS had been added but the schematron rule for checking the agency prefixes was not updated. I.e. typically the addition of a new namespace does not require a schematron rule update, except in the case where a new agency is involved. 

Test data:
[20231113_tests.zip](https://github.com/NASA-PDS/pds4-information-model/files/13341028/20231113_tests.zip)

**Comment by miguelp1986** [comment]
@jordanpadams Can I get some help testing this? Should I be running lddtool against the bundle files above?

```
lddtool151 -pl bundle_insight_FAIL_20231016.xml                                              ─╯

>>  INFO LDDTOOL Version: 15.1.0-SNAPSHOT
>>  INFO IM Version Id: 1.22.0.0
>>  INFO IM Namespace Id: pds
>>  INFO IM Label Version Id: 1.0
>>  INFO Date: Mon May 06 14:20:57 PDT 2024
>>  INFO PARENT_DIR: /usr/local/lddtool-15.1.0-SNAPSHOT/Data/

>>> ERROR Init:  - LDD Dictionary_Type not Found:TBD_dictionary_type  Defaulting to Discipline
>>> INFO Init:  - Config.Properties Namespace Id Using:pds
>>> WARNING Init:  - Config.Properties Namespace Id Not Found:TBD_Ingest_LDD

 -- LDDTool Execution Summary --
     1 warning(s)
     1 error(s)
     0 fatal error(s)

Input:

     - IM Version: 1M00
     - PDS4 Flag: true
     - LDD Flag: true

     - Ingest LDD(s): bundle_insight_FAIL_20231016.xml

Output:

     - ./PDS4_TBD_INGEST_LDD_1M00_0000x.xsd
     - ./PDS4_TBD_INGEST_LDD_1M00_0000x.sch
     - ./PDS4_TBD_INGEST_LDD_1M00_0000x.xml

>>  INFO Exit(1)
```

**Comment by jordanpadams** [comment]
@miguelp1986 The point of this ticket is that you can now have a `logical_identifier` beginning with `urn:kari:kpds`. If you take any label and set the PDS Core IM version to some older version of the IM (e.g. 1D00), and try to do this, it will fail for an invalid `logical_identifier`. With the last version of the IM, this should now be allowed.

**Comment by jordanpadams** [comment]
@miguelp1986 see attached for 1 success and 1 failure use case.

[Archive.zip](https://github.com/NASA-PDS/pds4-information-model/files/15236857/Archive.zip)
