### ISSUE TITLE
[namespace-registry]update namespace URL for KPDS

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds4-information-model#716]
### Namespace ID Requested

kplo

### Associated Namespace Details

https://github.com/NASA-PDS/operations/issues/474

### Engineering Details

- [ ] @jshughes update namespace registry

**Comment by jordanpadams** [comment]
Blocked per https://github.com/NASA-PDS/operations/issues/474#issuecomment-1870601138

**Comment by jordanpadams** [comment]
KPLO already exists, but need to update the namespace. renaming ticket.

**Comment by jshughes** [comment]
@jordanpadams @thareUSGS - Got the URL from Joo Hyeon, update to Namespace Registry queued.

**Comment by miguelp1986** [comment]
@jordanpadams can you provide some guidance in testing this issue? It looks related to issue #709
