### ISSUE TITLE
LDDTool is not creating valid URL for KPLO

### ISSUE THREAD

**Issue by jshughes** [NASA-PDS/pds4-information-model#738]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

1.	http://www.kari.re.kr/kpdsmission/kplo/v1 - Bad
2.	http://www.kari.re.kr/kpds/mission/kplo/v1 - Good

### 🕵️ Expected behavior

I expected namespace URL to be valid

### 📜 To Reproduce

1. execute LDDTool on KPLO LDD:

```
lddtool -lpJ ../ldd-kplo/src/PDS4_KPLO_IngestLDD.xml
```

2. Open the XSD and notice the namespace URL is `http://www.kari.re.kr/kpdsmission/kplo/v1`, which should be `http://www.kari.re.kr/kpds/mission/kplo/v1`

### 🖥 Environment Info

Linux system

### 📚 Version of Software Used

latest snapshot as of today

### 🦄 Related requirements

🦄 #xyz

**Comment by jordanpadams** [comment]
@jshughes unfortunately this still does not work with a past version of the IM. I tried updating the [1L00 IM config.properties](https://github.com/NASA-PDS/pds4-information-model/commit/60da3721b66e3f6bcf857ec503b1273cc7409cf4), but it did not work.

```
> lddtool -lpJ ../ldd-kplo/src/PDS4_KPLO_IngestLDD.xml -V 1L0
> cat ./PDS4_KPLO_1L00_1000.xsd | egrep kpdsmission
    targetNamespace="http://www.kari.re.kr/kpdsmission/kplo/v1"
    xmlns:kplo="http://www.kari.re.kr/kpdsmission/kplo/v1"
```

**Comment by jordanpadams** [comment]
NOTE: This works without the `-V` flag.

**Comment by jordanpadams** [comment]
Resolved per https://github.com/NASA-PDS/pds4-information-model/commit/60da3721b66e3f6bcf857ec503b1273cc7409cf4

**Comment by jshughes** [comment]
@jordanpadams Sorry for missing 1L00. Since there is a config.properties file for each version of the IM, I plan to clean up the prior versions. I assume that they will never actually be used but I don't like the clutter.
