### ISSUE TITLE
LDDTool -- missing a required namespace

### ISSUE THREAD

**Issue by rsjoyner** [NASA-PDS/pds4-information-model#741]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

There appears to be an error in omitting a required namespace when a schematron rule employs one of the external namespaces:

See enclosure for the Cassini_IngestLDD and the files that were built using this command:

lddtool_1E30_edited -lpJ1 -V 1J00 PDS4_CASSINI_IngestLDD.xml > log-a.txt
    <sch:rule context="cassini:CIRS_Cubes_Specific_Attributes">
      <sch:let name="map_projection" value="//cart:map_projection_name"/>
      <sch:let name="map_projection_rings" value="//cart:rings_map_projection_name"/>

These are the generated namespaces:
  <sch:ns uri="http://www.w3.org/2001/XMLSchema-instance" prefix="xsi"/>
  <sch:ns uri="http://pds.nasa.gov/pds4/pds/v1" prefix="pds"/>
  <sch:ns uri="http://pds.nasa.gov/pds4/mission/cassini/v1" prefix="cassini"/>

Note that the cartLDD is not listed.  And, the omission causes an error in the schematron.

These are the namespaces that should be generated:

  <sch:ns uri="http://www.w3.org/2001/XMLSchema-instance" prefix="xsi"/>
  <sch:ns uri="http://pds.nasa.gov/pds4/pds/v1" prefix="pds"/>
  <sch:ns uri="http://pds.nasa.gov/pds4/mission/cassini/v1" prefix="cassini"/>
  <sch:ns uri="http://pds.nasa.gov/pds4/cart/v1" prefix="cart"/>

### 🕵️ Expected behavior

From the schematron rules, I expected that these namespaces would be generated:

  <sch:ns uri="http://www.w3.org/2001/XMLSchema-instance" prefix="xsi"/>
  <sch:ns uri="http://pds.nasa.gov/pds4/pds/v1" prefix="pds"/>
  <sch:ns uri="http://pds.nasa.gov/pds4/mission/cassini/v1" prefix="cassini"/>
  <sch:ns uri="http://pds.nasa.gov/pds4/cart/v1" prefix="cart"/>

### 📜 To Reproduce

```bash
1. execute LDDTool using this command: lddtool_1E30_edited -lpJ1 -V 1J00 PDS4_CASSINI_IngestLDD.xml > log-a.txt
2. examine log.txt for errors.   NO errors but lots of Warnings.
3. examine the generated schematron file to see Error.
3. edit in the missing cartLDD namespace -- all is good.
...
```

### 🖥 Environment Info

```bash
- Version of this software is v14.3.0
- Operating System: windows
...
```

### 📚 Version of Software Used

- Version of this software is v14.3.0

### 🩺 Test Data / Additional context

See zip above.

### 🦄 Related requirements

🦄 #xyz

**Comment by jordanpadams** [comment]
Closing as invalid. See https://github.com/pds-data-dictionaries/ldd-cassini/pull/6#issuecomment-2013278205
