### ISSUE TITLE
LDDTool producing invalid XSD for Voyager LDD

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds4-information-model#744]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

Generated LDD from ldd-vgr repo output invalid XSD

### 🕵️ Expected behavior

I expected valid XSD

### 📜 To Reproduce

```
lddtool -lpJ PDS4_VGR_IngestLDD.xml
```

Open XSD and notice it is invalid.

> The element type "xs:documentation" must be terminated by the matching end-tag "</xs:documentation>".

### 🖥 Environment Info
Any

### 📚 Version of Software Used

v14.3.0

### 🩺 Test Data / Additional context

[PDS4_VGR_IngestLDD.xml.txt](https://github.com/NASA-PDS/pds4-information-model/files/14844348/PDS4_VGR_IngestLDD.xml.txt)

### 🦄 Related requirements

Blocking https://github.com/pds-data-dictionaries/ldd-vgr/pull/14

**Comment by jshughes** [comment]
@jordanpadams Sorry, but I have not been able to reproduce the error. 

The PDS4_VGR_IngestLDD.xml file referenced and downloaded from this issue contains the following definition:
    <name>filter_name</name>
			...
    <definition>Optical filter used for the image.
    Source Data Product Origin:  Keyword FILTER_NAME</definition>

LDDTool has been re-compiled from both my "main" after a pull, as well as my local JDK17 update branch. The results are consistently: 

  <xs:simpleType name="filter_name">
    <xs:annotation>
      <xs:documentation>Optical filter used for the image. Source Data
        Product Origin: Keyword FILTER_NAME</xs:documentation>

It is not clear where the offending text  "For details see the documentation at ..." is coming from.

**Comment by jordanpadams** [comment]
@jshughes sorry for the confusion. That ingest LDD was used to generate the schema (XSD). The generated schema is where the bug is. The IngestLDD is valid.

**Comment by jordanpadams** [comment]
Also, it looks like I was linking to the wrong LDD above. My apologies. The new one is on a branch associated with the pull request this is blocking. Sorry about that.

https://github.com/pds-data-dictionaries/ldd-vgr/blob/v1.0/src/PDS4_VGR_IngestLDD.xml

**Comment by jshughes** [comment]
@jordanpadams Found the problem. A quick fix is to add a blank after the last URL, before the </definition> tag, in the PDS4_VGR_IngestLDD.xml file. 
I will be fixing the code.

**Comment by jordanpadams** [comment]
Awesome. Thanks @jshughes . Sorry for the confusion
