### ISSUE TITLE
[namespace-registry] add new namespace VIPER

### ISSUE THREAD

**Issue by mnhughes** [NASA-PDS/pds4-information-model#748]
### Namespace ID Requested

VIPER

### Associated Namespace Details

https://github.com/NASA-PDS/operations/issues/504

### Engineering Details

- [ ] @jshughes update namespace registry

**Comment by c-suh** [comment]
@mnhughes hello! Please create a ticket with [this Operations issue template](https://github.com/NASA-PDS/operations/issues/new?assignees=jordanpadams%2Cc-suh&labels=enhancement%2Cldd-request%2Cneeds%3Atriage%2Cp.must-have%2Csprint-backlog&projects=&template=-ldd-request--initialize-new-pds-ldd.yml&title=%5Bldd-request%5D+Create+new+LDD+%22%3Cproposed+namespace+ID%3E%22) and fill in the requested details to create the namespace "VIPER". We will be able to proceed once we have the information there. Thank you.

**Comment by jshughes** [comment]
@c-suh Just checking but it seems that the template does not yet have any of the required information. Can I assume that the requestor will be providing it?
