### ISSUE TITLE
webpage links are not working

### ISSUE THREAD

**Issue by plawton-umd** [NASA-PDS/pds4-information-model#754]
### Checked for duplicates

No - I haven't checked

### 🐛 Describe the bug

From the page https://nasa-pds.github.io/pds4-information-model/model-lddtool/index.html
when I clicked on "current"
it returned "Not Found".

From the same staring page, 
when I clicked on "10.1.2"
it returned 404

### 🕵️ Expected behavior

I expected it to return the information on the pages that those links are for.

### 📜 To Reproduce

```bash
1. go to https://nasa-pds.github.io/pds4-information-model/model-lddtool/index.html
2. click on "current"
3. go to https://nasa-pds.github.io/pds4-information-model/model-lddtool/index.html
4. click on 10.1.1
...
```

### 🖥 Environment Info

```bash
- Version of this software [e.g. vX.Y.Z]
- Operating System: [e.g. MacOSX with Docker Desktop vX.Y]
...
```

### 🦄 Related requirements

🦄 #xyz

**Comment by jordanpadams** [comment]
Blocked by https://github.com/NASA-PDS/roundup-action/issues/136

**Comment by jordanpadams** [comment]
@plawton-umd sorry for the issue here. the latest version for download can be found here: https://github.com/NASA-PDS/pds4-information-model/releases/latest

**Comment by jordanpadams** [comment]
resolved by https://github.com/NASA-PDS/pds4-information-model/pull/757
