### ISSUE TITLE
As a data provider, I want to add additional content to Investigation context products

### ISSUE THREAD

**Issue by jshughes** [NASA-PDS/pds4-information-model#765]
### Checked for duplicates

Yes - I've already checked

### 🧑‍🔬 User Persona(s)

Data Engineer, Data Provider

### 💪 Motivation

The additional information can be used for Search and providing more information to users.

### Acceptance Criteria

TBD

### ⚙️ Engineering Details

The initial plan is to enhance the Investigation (Mission) class for Product_Context as follows:

Prototype the enhanced Investigation class Protégé and generated XML template. 

1. Add a terse description allowing no more than 255 characters
2. Add prioritized Alias and Acronym lists - Done
3. Add Mission Phase Information - Done
4. Update Modification Details to include Author and Editor Lists

Create SCRs for modifications to Investigation Context Products to get DDWG approval

https://github.com/NASA-PDS/PDS4-CCB/issues/34
https://github.com/NASA-PDS/PDS4-CCB/issues/35
https://github.com/NASA-PDS/PDS4-CCB/issues/36.

### 🎉 Integration & Test

TBD

**Comment by tloubrieu-jpl** [comment]
@jshughes is making process in this ticket.

**Comment by matthewtiscareno** [comment]
> DDWG verbally approved the changes.

I strongly disagree with this characterization of the most recent DDWG meeting.  

Concerns were raised, and the conversation has only begun.  Please see [CCB#34](https://github.com/NASA-PDS/PDS4-CCB/issues/34), [CCB#35](https://github.com/NASA-PDS/PDS4-CCB/issues/35), and [CCB#36](https://github.com/NASA-PDS/PDS4-CCB/issues/36).

**Comment by jordanpadams** [comment]
> DDWG verbally approved the changes.

@matthewtiscareno this was taken out of context of our stand-up meeting. I think this may have been placed on the wrong ticket. Apologies for the confusion.

**Comment by jordanpadams** [comment]
Skipping I&T because the actual SCRs will include the appropriate test cases
