### ISSUE TITLE
[namespace-registry] add new namespace juice

### ISSUE THREAD

**Issue by tcornet** [NASA-PDS/pds4-information-model#803]
### Namespace ID Requested

juice and all instruments associated to JUICE 
(https://s2e2.cosmos.esa.int/confluence/display/PSAPUB1/PSA+namespace+registry)

### Associated Namespace Details

https://s2e2.cosmos.esa.int/confluence/display/PSAPUB1/PSA+namespace+registry

### Engineering Details

- [ ] @jshughes update namespace registry

**Comment by jordanpadams** [comment]
@tcornet would you like a repo here to manage this LDD?

https://github.com/pds-data-dictionaries/ldd-template

**Comment by tcornet** [comment]
@jordanpadams for now it should not be necessary. Thank you for asking!
