### ISSUE TITLE
LDDTool does not resolve the JUICE namespaces with IM 1J00

### ISSUE THREAD

**Issue by tcornet** [NASA-PDS/pds4-information-model#818]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

I tried to build a JUICE instrument dictionary following the update of the JUICE namespaces in the LDDTool 15.2.0-SNAPSHOT but the namespace id's are not resolved using IM 1J00, which we are using. (with IM 1N00 it works)

### 🕵️ Expected behavior

I expected the namespaces to be resolved with 1J00. 

### 📜 To Reproduce

```bash
execute lddtool -ldp -V 1J00 Some_Ingest_File.xml
```

### 📚 Version of Software Used

lddtool 15.2.0-SNAPSHOT

**Comment by msbentley** [comment]
We had this once before @jshughes, if I remember rightly, where the new namespaces were not backported to the config.properties file for previous IM versions. Is there something we should do procedurally to make sure this happens?

**Comment by jshughes** [comment]
Given the current software, indicating the desired IM version should be sufficient. However there is a planned fix that addresses this issue so that the IM version will not matter.

**Comment by jordanpadams** [comment]
@jshughes it sounds like they need IM 1J00, and the config for JUICE was not ported back that far. As @msbentley noted, per [the PR when this update was made](https://github.com/NASA-PDS/pds4-information-model/commit/248c1cc05bb6bb0baf6dc0c0fded9f5e0f5eaf9d#diff-2226fc359fd8f90dcbf8092338eddb0a090f4b7e9e168e2f00bd24d643f4d872), it looks like we only made this update in the current [`config.properties`](https://github.com/NASA-PDS/pds4-information-model/blob/main/model-ontology/src/ontology/Data/config.properties#L1037), but not in past IM versions, i.e. the [1J00 config.properties file](https://github.com/NASA-PDS/pds4-information-model/blob/main/model-ontology/src/ontology/Data/1J00/config.properties). Can we make this update?

**Comment by jordanpadams** [comment]
Fixed per https://github.com/NASA-PDS/pds4-information-model/pull/821
