### ISSUE TITLE
Schematron throws duplicate errors for `kernel_type` checks

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds4-information-model#820]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

When I tested #797 , I get duplicate error messages from the schematron

### 🕵️ Expected behavior

I expected only one error message

### 📜 To Reproduce

```bash
# generate core LDD
$ lddtool -p
...

# generate GEOM LDD
$ lddtool -lp model-lddtool/src/test/resources/github797/PDS4_GEOM_IngestLDD.xml
...

# Move the XSD/SCH to be alongside the core
$ mv PDS4_GEOM_1N00_1970.* export/

# Try to validate
$ validate --target model-lddtool/src/test/resources/github797/u5.xml model-lddtool/src/test/resources/github797/test_label1_FAIL.xml -S export/*.sch -x export/*.xsd

...

  FAIL: file:/Users/jpadams/proj/pds/pdsen/workspace/pds4-information-model/model-lddtool/src/test/resources/github797/u5.xml
      ERROR  [error.label.schema]   line 88, 42: cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://pds.nasa.gov/pds4/pds/v1":kernel_type}'. One of '{"http://pds.nasa.gov/pds4/geom/v1":kernel_type, "http://pds.nasa.gov/pds4/geom/v1":spice_kernel_file_name}' is expected.
      ERROR  [error.label.schema]   line 92, 42: cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://pds.nasa.gov/pds4/pds/v1":kernel_type}'. One of '{"http://pds.nasa.gov/pds4/geom/v1":kernel_type, "http://pds.nasa.gov/pds4/geom/v1":spice_kernel_file_name}' is expected.

...

  FAIL: file:/Users/jpadams/proj/pds/pdsen/workspace/pds4-information-model/model-lddtool/src/test/resources/github797/test_label1_FAIL.xml
      ERROR  [error.label.schematron]   line 101, 43: The attribute geom:SPICE_Kernel_Identification/geom:kernel_type must be equal to one of the following values 'CK', 'DBK', 'DSK', 'EK', 'FK', 'IK', 'LSK', 'MK', 'PCK', 'SCLK', 'SPK'.
      ERROR  [error.label.schematron]   line 114, 43: The attribute geom:SPICE_Kernel_Identification/geom:kernel_type must be equal to one of the following values 'CK', 'DBK', 'DSK', 'EK', 'FK', 'IK', 'LSK', 'MK', 'PCK', 'SCLK', 'SPK'.

...

```

### 🖥 Environment Info

MacOSx

### 📚 Version of Software Used

main

### 🩺 Test Data / Additional context

~See branch: https://github.com/NASA-PDS/pds4-information-model/tree/rchenatjpl-patch-1~

Data is more specifically here: https://github.com/NASA-PDS/pds4-information-model/tree/main/model-lddtool/src/test/resources/github797

### 🦄 Related requirements

🦄 #797

**Comment by jshughes** [comment]
@jordanpadams The reason two errors are thrown is that the test file contains two errors. See "Bad kernel_type #1" and "Bad kernel_type #2" in the snippet below from test_label1_FAIL.xml. I am not sure why there are two tests. Using Oxygen I also got two errors using test_label1_FAIL.xml. I also used Oxygen against the the Rings' file, u5_lco_250cm_2200nm_counts-v-time_rings_egress.xml. The one expected error was thrown.

        <Discipline_Area>
            <geom:Geometry>
                <geom:SPICE_Kernel_Files>
                    <geom:SPICE_Kernel_Identification>
                        
                        <geom:kernel_type>FOO</geom:kernel_type>
                        ...
                    </geom:SPICE_Kernel_Identification>
                    
                    <geom:SPICE_Kernel_Identification>
                        <geom:kernel_type>BPC</geom:kernel_type>

**Comment by jordanpadams** [comment]
Bah you are right!
