### ISSUE TITLE
CCB-10: Schematron/Schema Version Conflict (PDS-JIRA-366)

### ISSUE THREAD

**Issue by rsjoyner** [NASA-PDS/pds4-information-model#838]
### 🦄 Sibling SCR

NASA-PDS/PDS4-CCB#10

### Original JIRA SCR
[CCB-366_Schematron_Schema Version Conflict.pdf](https://github.com/NASA-PDS/PDS4-CCB/files/14126964/CCB-366_Schematron_Schema.Version.Conflict.pdf)

### Priority

Urgent

### IM Build

1.22.0

### Checked for duplicates

Yes - I've already checked

### Problem Statement

Schematron/Schema Version Conflict – SR and possibly DPH need to be updated to explicitly note this is invalid.

In a product label, if you have schematron for a specific model (like 1.20.0.0), make sure that the schema model reference is also that same version (1.20.0.0). Currently, there is nothing in the standard that documents "IM version should match between schematron and schema". This seems like an assumed requirement, but it should be called out explicitly in the standard.

Validate now checks for this and throws a WARNING (it did not prior to v3.3.0).

### Additional Details

https://pds-jira.jpl.nasa.gov/browse/CCB-366

### Applicable Components

Data Providers Handbook (DPH), Standards Reference, PDS Tools

### Proposed Solution

See Requested Changes

### Requested Changes

(1) Update SR and DPH to reflect that the schematron reference for a specific version (e.g., 1.20.0.0) is identical to the schema model reference (i.e., the 2 references to the specific versions of the schematron and schema  'match').

### Applicable Attachments

1. The PDF specifies the proposed changes to the SR.

[StdRef_and_DPH_updates_20240123.docx](https://github.com/NASA-PDS/PDS4-CCB/files/14126910/StdRef_and_DPH_updates_20240123.docx)

Amended updates to the SR and DPH (from comments from mace-space Mar-20):

[StdRef_and_DPH_updates_20240320.zip](https://github.com/user-attachments/files/16851367/StdRef_and_DPH_updates_20240320.zip)

### Impact Statement

Impact:
  -- Standards Reference -- The requested change has a minimal impact on the Standards Reference.
  -- DPH -- The requested change has a minimal impact on the DPH.
  		
No Impact:
  -- Information Model
  -- Concepts Document
  -- APG
  -- External Agencies
  -- ISO Standards
  -- PDS Tools
  -- PDS Website
  -- PAG

Archives made public previous to the validate updates that have mismatched schemas/schematrons may now fail validation.

### Technical Assessment

The request is to update the SR and DPH to state that the schematron reference for a specific version shall be identical to the schema model reference. This change explicitly states an assumed requirement. This change request is reasonable.

Validate will need to be updated in order perform this check (2 work days).

This was already completed here:
- https://github.com/NASA-PDS/validate/issues/628

### System Impact

Past archives with mismatched schemas/schematrons may now fail validation.

### DDWG Notes

CCB#10 - Item Passed: 7 Yes (ATM, EN, GEO, CIS, PPI, RMS, SBN), 2 Abs (NAIF, RS), 1 NV (IPDA)

### CCB Processing Summary

Item Passed: 7 Yes (ATM, GEO, CIS, PPI, RMS, SBN, IPDA)

### Added to parent epic?

Will do

**Comment by jordanpadams** [comment]
Documentation update completed and sent to document review team
