### ISSUE TITLE
lddtool -v creates/overwrites output directory and files

### ISSUE THREAD

**Issue by plawton-umd** [NASA-PDS/pds4-information-model#848]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

When I typed lddtool -v, 

the directory and list of files under "Output:" in the output to the screen (below) were created.
Based on the lddtool -h information, only output to the screen with the version number was expected
(the first 4 lines in the output to the screen).  Output directory and files were not expected.

from lddtool -h
  -v, --version          Returns  the  LDDTool   version  number  (default:
                                 false)

Output to screen: 

LDDTool Version: 15.2.3
Built with IM Version: 1.23.0.0
Build Date: 2024-11-20 02:55:26
Configured IM Versions: [1N00, 1M00, 1L00, 1K00, 1J00, 1I00, 1H00, 1G00, 1F00, 1E00, 1D00, 1C00, 1B10, 1B00]
 

\>>  INFO DMDoc Version: 15.2.3
\>>  INFO IM Version Id: 1.23.0.0
\>>  INFO IM Namespace Id: pds
\>>  INFO IM Label Version Id: 1.0
\>>  INFO Date: Thu Nov 21 09:04:26 EST 2024
\>>  INFO PARENT_DIR: /n/sbnops/lcltools/install/lddtool-15.2.3/Data/

 -- IMTool Execution Summary --
     0 warning(s)
     0 error(s)
     0 fatal error(s)

Input:

     - IM Version: 1N00
     - Version Flag: true

     - Ingest LDD(s): 

Output:

     - ./index_1N00.html
     - ./export/PDS4_PDS_1N00.xsd
     - ./export/PDS4_PDS_1N00.sch
     - ./export/PDS4_PDS_1N00.xml
     - ./export/PDS4_PDS_1N00.JSON
     - ./export/PDS4_PDS_DD_1N00.xml

\>>  INFO Exit(0)

### 🕵️ Expected behavior

I expected only the first 4 lines of the output to the screen.  No created/overwritten directories or file.

LDDTool Version: 15.2.3
Built with IM Version: 1.23.0.0
Build Date: 2024-11-20 02:55:26
Configured IM Versions: [1N00, 1M00, 1L00, 1K00, 1J00, 1I00, 1H00, 1G00, 1F00, 1E00, 1D00, 1C00, 1B10, 1B00]

### 📜 To Reproduce

```bash
1. lddtool -v
2.
3.
...
```

### 🖥 Environment Info

```bash
- Version of this software 15.2.3
- Operating System: Linux
...
```

### 🦄 Related requirements

🦄 #xyz

**Comment by jordanpadams** [comment]
@plawton-umd got it. we will take a look.

**Comment by jordanpadams** [comment]
Skipping I&T. PR tested.
