### ISSUE TITLE
lddtool -h returns expected information twice and then error messages 

### ISSUE THREAD

**Issue by plawton-umd** [NASA-PDS/pds4-information-model#849]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

When I did lddtool -h, it returned

usage: LDDTool [-h] [-p] [-l] [-d] [-D] [-J] [-m] [-M] [-n] [-N] [-1] [-T]
               [-O] [-o] [-C] [-v]
               [-V {1B00,1B10,1C00,1D00,1E00,1F00,1G00,1H00,1I00,1J00,1K00,1L00,1M00,1N00}]
               [fileNameArr [fileNameArr ...]]

LDDTool process control:

positional arguments:
  fileNameArr            Ingest_LDD files to process.

named arguments:
  -h, --help             show this help message and exit
  -p, --PDS4 processing  Set the context to PDS4 (default: false)
  -l, --LDD              Process one or  more  local  data dictionary input
                         files (default: false)
  -d, --discipline       Omit the term "mission"  from  the  namespace of a
                         dictionary (default: false)
  -D, --DataDict         Write the Data  Dictionary  DocBook file (default:
                         false)
  -J, --JSON             Write the  data  dictionary  to  a  JSON formatted
                         file (default: false)
  -m, --merge            Generate file to merge  the  local dictionary into
                         the master dictionary (default: false)
  -M, --Mission          This option has no  effect  starting  with PDS4 IM
                         Version 1.14.0.0. See  the  LDDTool Usage document
                         for  more  information  on  how  to  provide  this
                         information. (default: false)
  -n, --nuance           Write  nuance   property   maps   to   LDD  schema
                         annotation in JSON (default: false)
  -N, --Namespace        Print the list  of  configured  namespaces  to the
                         log (default: false)
  -1, --IM Spec          Write the Information  Model  Specification for an
                         LDD (default: false)
  -T, --TermMap          Terminological   mapping   to    alternate   names
                         (default: false)
  -O, --OWL/RDF/TTL      OWL/RDF/TTL   output    in    TTL    format    (IM
                         Classification) (default: false)
  -o, --OWL/RDF          OWL/RDF  output   in   RDF   format   (IM  Export)
                         (default: false)
  -C, --Custom           Customized  processing  and   reporting  (default:
                         false)
  -v, --version          Returns  the  LDDTool   version  number  (default:
                         false)
  -V {1B00,1B10,1C00,1D00,1E00,1F00,1G00,1H00,1I00,1J00,1K00,1L00,1M00,1N00}, --IM Version {1B00,1B10,1C00,1D00,1E00,1F00,1G00,1H00,1I00,1J00,1K00,1L00,1M00,1N00}
                         Set the IM Version (default: 1N00)
>>  INFO Exit(0)
usage: LDDTool [-h] [-p] [-l] [-d] [-D] [-J] [-m] [-M] [-n] [-N] [-1] [-T]
               [-O] [-o] [-C] [-v]
               [-V {1B00,1B10,1C00,1D00,1E00,1F00,1G00,1H00,1I00,1J00,1K00,1L00,1M00,1N00}]
               [fileNameArr [fileNameArr ...]]

LDDTool process control:

positional arguments:
  fileNameArr            Ingest_LDD files to process.

named arguments:
  -h, --help             show this help message and exit
  -p, --PDS4 processing  Set the context to PDS4 (default: false)
  -l, --LDD              Process one or  more  local  data dictionary input
                         files (default: false)
  -d, --discipline       Omit the term "mission"  from  the  namespace of a
                         dictionary (default: false)
  -D, --DataDict         Write the Data  Dictionary  DocBook file (default:
                         false)
  -J, --JSON             Write the  data  dictionary  to  a  JSON formatted
                         file (default: false)
  -m, --merge            Generate file to merge  the  local dictionary into
                         the master dictionary (default: false)
  -M, --Mission          This option has no  effect  starting  with PDS4 IM
                         Version 1.14.0.0. See  the  LDDTool Usage document
                         for  more  information  on  how  to  provide  this
                         information. (default: false)
  -n, --nuance           Write  nuance   property   maps   to   LDD  schema
                         annotation in JSON (default: false)
  -N, --Namespace        Print the list  of  configured  namespaces  to the
                         log (default: false)
  -1, --IM Spec          Write the Information  Model  Specification for an
                         LDD (default: false)
  -T, --TermMap          Terminological   mapping   to    alternate   names
                         (default: false)
  -O, --OWL/RDF/TTL      OWL/RDF/TTL   output    in    TTL    format    (IM
                         Classification) (default: false)
  -o, --OWL/RDF          OWL/RDF  output   in   RDF   format   (IM  Export)
                         (default: false)
  -C, --Custom           Customized  processing  and   reporting  (default:
                         false)
  -v, --version          Returns  the  LDDTool   version  number  (default:
                         false)
  -V {1B00,1B10,1C00,1D00,1E00,1F00,1G00,1H00,1I00,1J00,1K00,1L00,1M00,1N00}, --IM Version {1B00,1B10,1C00,1D00,1E00,1F00,1G00,1H00,1I00,1J00,1K00,1L00,1M00,1N00}
                         Set the IM Version (default: 1N00)
Exception in thread "main" net.sourceforge.argparse4j.helper.HelpScreenException: Help Screen
	at net.sourceforge.argparse4j.impl.action.HelpArgumentAction.run(HelpArgumentAction.java:52)
	at net.sourceforge.argparse4j.inf.ArgumentAction.run(ArgumentAction.java:106)
	at net.sourceforge.argparse4j.internal.ArgumentImpl.run(ArgumentImpl.java:494)
	at net.sourceforge.argparse4j.internal.ArgumentParserImpl.processArg(ArgumentParserImpl.java:950)
	at net.sourceforge.argparse4j.internal.ArgumentParserImpl.parseArgs(ArgumentParserImpl.java:844)
	at net.sourceforge.argparse4j.internal.ArgumentParserImpl.parseArgsAtOffsetZero(ArgumentParserImpl.java:703)
	at net.sourceforge.argparse4j.internal.ArgumentParserImpl.parseArgs(ArgumentParserImpl.java:572)
	at net.sourceforge.argparse4j.internal.ArgumentParserImpl.parseArgs(ArgumentParserImpl.java:557)
	at gov.nasa.pds.model.plugin.DMDocument.getArgumentParserNamespace(DMDocument.java:1226)
	at gov.nasa.pds.model.plugin.DMDocument.run(DMDocument.java:348)
	at gov.nasa.pds.model.plugin.DMDocument.main(DMDocument.java:327)

### 🕵️ Expected behavior

I expected the help information once and no errors messages - as below.

usage: LDDTool [-h] [-p] [-l] [-d] [-D] [-J] [-m] [-M] [-n] [-N] [-1] [-T]
               [-O] [-o] [-C] [-v]
               [-V {1B00,1B10,1C00,1D00,1E00,1F00,1G00,1H00,1I00,1J00,1K00,1L00,1M00,1N00}]
               [fileNameArr [fileNameArr ...]]

LDDTool process control:

positional arguments:
  fileNameArr            Ingest_LDD files to process.

named arguments:
  -h, --help             show this help message and exit
  -p, --PDS4 processing  Set the context to PDS4 (default: false)
  -l, --LDD              Process one or  more  local  data dictionary input
                         files (default: false)
  -d, --discipline       Omit the term "mission"  from  the  namespace of a
                         dictionary (default: false)
  -D, --DataDict         Write the Data  Dictionary  DocBook file (default:
                         false)
  -J, --JSON             Write the  data  dictionary  to  a  JSON formatted
                         file (default: false)
  -m, --merge            Generate file to merge  the  local dictionary into
                         the master dictionary (default: false)
  -M, --Mission          This option has no  effect  starting  with PDS4 IM
                         Version 1.14.0.0. See  the  LDDTool Usage document
                         for  more  information  on  how  to  provide  this
                         information. (default: false)
  -n, --nuance           Write  nuance   property   maps   to   LDD  schema
                         annotation in JSON (default: false)
  -N, --Namespace        Print the list  of  configured  namespaces  to the
                         log (default: false)
  -1, --IM Spec          Write the Information  Model  Specification for an
                         LDD (default: false)
  -T, --TermMap          Terminological   mapping   to    alternate   names
                         (default: false)
  -O, --OWL/RDF/TTL      OWL/RDF/TTL   output    in    TTL    format    (IM
                         Classification) (default: false)
  -o, --OWL/RDF          OWL/RDF  output   in   RDF   format   (IM  Export)
                         (default: false)
  -C, --Custom           Customized  processing  and   reporting  (default:
                         false)
  -v, --version          Returns  the  LDDTool   version  number  (default:
                         false)
  -V {1B00,1B10,1C00,1D00,1E00,1F00,1G00,1H00,1I00,1J00,1K00,1L00,1M00,1N00}, --IM Version {1B00,1B10,1C00,1D00,1E00,1F00,1G00,1H00,1I00,1J00,1K00,1L00,1M00,1N00}
                         Set the IM Version (default: 1N00)

### 📜 To Reproduce

```bash
1. lddtool -h
2.
3.
...
```

### 🖥 Environment Info

```bash
- Version of this software 15.2.3
- Operating System: Linux
...
```

### 🦄 Related requirements

🦄 #xyz

**Comment by jordanpadams** [comment]
Skipping I&T. Tested during PR review. https://github.com/NASA-PDS/pds4-information-model/pull/853
