### ISSUE TITLE
LDDTool: Enhance software error handling and logging for improved usability

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds4-information-model#87]

**Comment by jordanpadams** [comment]
@jshughes can you provide a status on this?

**Comment by jordanpadams** [comment]
Delay rationale: Delayed due to reprioritization of other PDS4 standards efforts related to DDWG.

**Comment by jshughes** [comment]
Completing the first phase of changes intended to address all issues associated with error handling and logging. Currently addressing review comments from J. Padams.

**Comment by jordanpadams** [comment]
June schedule status: delayed due to increased scope from comments from @jordanpadams . still on schedule for delivery by end of build cycle.
